use crate::error::{GuiError, GuiResult};

use super::{validate_bounded_text, TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES};

/// Namespace reserved for identities generated by the A3S runtime.
pub const TSX_PROTOCOL_V1_GENERATED_ID_NAMESPACE: &str = "a3s:";
/// Prefix for Node-local function-component instance identities.
pub const TSX_PROTOCOL_V1_COMPONENT_IDENTITY_PREFIX: &str = "a3s:c1:";
/// Prefix for action ids derived from native key paths and event props.
pub const TSX_PROTOCOL_V1_AUTOMATIC_ACTION_ID_PREFIX: &str = "a3s:a1:";

pub(super) fn validate_tsx_action_id(field: &str, value: &str) -> GuiResult<()> {
    validate_bounded_text(field, value, TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES)?;
    if value.starts_with(TSX_PROTOCOL_V1_GENERATED_ID_NAMESPACE) {
        if is_canonical_automatic_action_id_v1(value) {
            return Ok(());
        }
        return Err(GuiError::host(format!(
            "{field} uses the reserved {TSX_PROTOCOL_V1_GENERATED_ID_NAMESPACE:?} namespace without a canonical automatic action identity"
        )));
    }
    if is_canonical_javascript_array_index(value) {
        return Err(GuiError::host(format!(
            "{field} cannot be a canonical JavaScript array-index name"
        )));
    }
    Ok(())
}

fn is_canonical_automatic_action_id_v1(value: &str) -> bool {
    let Some(encoded) = value.strip_prefix(TSX_PROTOCOL_V1_AUTOMATIC_ACTION_ID_PREFIX) else {
        return false;
    };
    let bytes = encoded.as_bytes();
    let mut cursor = 0;
    let mut segments = 0;
    while cursor < bytes.len() {
        let length_start = cursor;
        while cursor < bytes.len() && bytes[cursor].is_ascii_digit() {
            cursor += 1;
        }
        if cursor == length_start || cursor == bytes.len() || bytes[cursor] != b':' {
            return false;
        }
        if bytes[length_start] == b'0' && cursor - length_start > 1 {
            return false;
        }
        let mut length = 0_usize;
        for digit in &bytes[length_start..cursor] {
            let Some(next) = length
                .checked_mul(10)
                .and_then(|value| value.checked_add(usize::from(*digit - b'0')))
            else {
                return false;
            };
            length = next;
        }
        cursor += 1;
        let Some(end) = cursor.checked_add(length) else {
            return false;
        };
        if length == 0 || end > bytes.len() || std::str::from_utf8(&bytes[cursor..end]).is_err() {
            return false;
        }
        cursor = end;
        segments += 1;
    }
    segments >= 2
}

fn is_canonical_javascript_array_index(value: &str) -> bool {
    if value == "0" {
        return true;
    }
    if value.starts_with('0') || !value.bytes().all(|byte| byte.is_ascii_digit()) {
        return false;
    }
    value
        .parse::<u64>()
        .is_ok_and(|index| index < u64::from(u32::MAX))
}
