use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};

use ts_rs::{Config, TypeVisitor, TS};

use crate::error::{GuiError, GuiResult};

use super::{
    TsxClientMessageV1, TsxHostMessageV1, TSX_PROTOCOL_NAME, TSX_PROTOCOL_V1_HARD_MAX_FRAME_BYTES,
    TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES, TSX_PROTOCOL_V1_MAX_DIAGNOSTICS,
    TSX_PROTOCOL_V1_MAX_DIAGNOSTIC_BYTES, TSX_PROTOCOL_V1_MAX_ELEMENT_ID_BYTES,
    TSX_PROTOCOL_V1_MAX_EVENT_ITEMS, TSX_PROTOCOL_V1_MAX_EVENT_VALUE_BYTES,
    TSX_PROTOCOL_V1_MAX_SAFE_INTEGER, TSX_PROTOCOL_V1_MAX_SESSION_ID_BYTES,
    TSX_PROTOCOL_V1_MAX_VERSION_BYTES,
};

pub const TSX_TYPESCRIPT_PROTOCOL_RELATIVE_PATH: &str =
    "packages/typescript/src/generated/protocol.ts";

/// Generates the checked-in TypeScript protocol module from the Rust wire DTOs.
pub fn generate_tsx_typescript_protocol_v1() -> GuiResult<String> {
    let declarations = tsx_typescript_protocol_declarations_v1()?;
    let fingerprint = tsx_typescript_protocol_fingerprint_v1(&declarations);

    Ok(format!(
        "// @generated by `cargo run --locked --no-default-features --features typescript-schema --bin a3s-gui-generate-tsx-protocol -- --write`.\n\
// Do not edit this file manually; change the versioned Rust wire DTOs instead.\n\
// Protocol: {TSX_PROTOCOL_NAME} v1\n\
// Declaration fingerprint: fnv1a64:{fingerprint}\n\
// Every numeric Rust u64 below is rejected above Number.MAX_SAFE_INTEGER.\n\
// Arbitrary 64-bit render fingerprints use fixed lowercase hexadecimal strings.\n\n\
export const TSX_PROTOCOL_DECLARATION_FINGERPRINT_V1 = \"fnv1a64:{fingerprint}\" as const;\n\n\
{declarations}"
    ))
}

/// Generates only the fingerprinted declaration body.
pub fn tsx_typescript_protocol_declarations_v1() -> GuiResult<String> {
    let config = Config::new().with_large_int("number");
    let mut collector = DeclarationCollector::new(&config);
    collector.collect::<TsxClientMessageV1>();
    collector.collect::<TsxHostMessageV1>();
    let declarations = collector.finish()?;

    let mut output = format!(
        "export const TSX_PROTOCOL_NAME = {TSX_PROTOCOL_NAME:?} as const;\n\
export const TSX_PROTOCOL_VERSION_V1 = 1 as const;\n\
export const TSX_PROTOCOL_V1_HARD_MAX_FRAME_BYTES = {TSX_PROTOCOL_V1_HARD_MAX_FRAME_BYTES} as const;\n\
export const TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES = {TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES} as const;\n\
export const TSX_PROTOCOL_V1_MAX_DIAGNOSTIC_BYTES = {TSX_PROTOCOL_V1_MAX_DIAGNOSTIC_BYTES} as const;\n\
export const TSX_PROTOCOL_V1_MAX_DIAGNOSTICS = {TSX_PROTOCOL_V1_MAX_DIAGNOSTICS} as const;\n\
export const TSX_PROTOCOL_V1_MAX_ELEMENT_ID_BYTES = {TSX_PROTOCOL_V1_MAX_ELEMENT_ID_BYTES} as const;\n\
export const TSX_PROTOCOL_V1_MAX_EVENT_ITEMS = {TSX_PROTOCOL_V1_MAX_EVENT_ITEMS} as const;\n\
export const TSX_PROTOCOL_V1_MAX_EVENT_VALUE_BYTES = {TSX_PROTOCOL_V1_MAX_EVENT_VALUE_BYTES} as const;\n\
export const TSX_PROTOCOL_V1_MAX_SAFE_INTEGER = {TSX_PROTOCOL_V1_MAX_SAFE_INTEGER} as const;\n\
export const TSX_PROTOCOL_V1_MAX_SESSION_ID_BYTES = {TSX_PROTOCOL_V1_MAX_SESSION_ID_BYTES} as const;\n\
export const TSX_PROTOCOL_V1_MAX_VERSION_BYTES = {TSX_PROTOCOL_V1_MAX_VERSION_BYTES} as const;\n\
export type TsxSafeIntegerV1 = number;\n\n"
    );

    let declarations = declarations
        .values()
        .map(|declaration| {
            let declaration = declaration
                .lines()
                .map(str::trim_end)
                .collect::<Vec<_>>()
                .join("\n");
            format!("export {declaration}")
        })
        .collect::<Vec<_>>()
        .join("\n\n");
    output.push_str(&declarations);
    output.push('\n');
    Ok(output)
}

/// Stable FNV-1a fingerprint for the declaration body.
pub fn tsx_typescript_protocol_fingerprint_v1(declarations: &str) -> String {
    let mut hash = 0xcbf29ce484222325_u64;
    for byte in declarations.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{hash:016x}")
}

struct DeclarationCollector<'a> {
    config: &'a Config,
    seen: HashSet<TypeId>,
    declarations: BTreeMap<String, String>,
    error: Option<String>,
}

impl<'a> DeclarationCollector<'a> {
    fn new(config: &'a Config) -> Self {
        Self {
            config,
            seen: HashSet::new(),
            declarations: BTreeMap::new(),
            error: None,
        }
    }

    fn collect<T: TS + 'static + ?Sized>(&mut self) {
        if self.error.is_some() || !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        if T::output_path().is_none() {
            return;
        }

        let name = T::ident(self.config);
        let declaration = T::decl(self.config);
        if let Some(existing) = self.declarations.get(&name) {
            if existing != &declaration {
                self.error = Some(format!(
                    "TypeScript declaration name {name:?} was emitted with conflicting definitions"
                ));
                return;
            }
        } else {
            self.declarations.insert(name, declaration);
        }
        T::visit_dependencies(self);
    }

    fn finish(self) -> GuiResult<BTreeMap<String, String>> {
        match self.error {
            Some(error) => Err(GuiError::host(error)),
            None => Ok(self.declarations),
        }
    }
}

impl TypeVisitor for DeclarationCollector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        self.collect::<T>();
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::Path;

    use super::*;

    #[test]
    fn generated_protocol_contains_strict_wire_spellings() {
        let generated = generate_tsx_typescript_protocol_v1().unwrap();
        assert!(generated.contains("export type TsxClientMessageV1 ="));
        assert!(generated.contains("export type TsxHostMessageV1 ="));
        assert!(generated.contains("\"type\": \"render\""));
        assert!(generated.contains("importSource?: string | null"));
        assert!(!generated.contains("import_source"));
        assert!(generated.contains("protocolVersion: number"));
        assert!(generated.contains("renderRevision: number"));
        assert!(generated.contains("layoutFingerprint: TsxFingerprintV1"));
        assert!(generated.contains("type TsxFingerprintV1 = string"));
        assert!(generated
            .contains("export const TSX_PROTOCOL_V1_HARD_MAX_FRAME_BYTES = 16777216 as const;"));
        assert!(
            generated.contains("export const TSX_PROTOCOL_V1_MAX_EVENT_ITEMS = 65536 as const;")
        );
        assert!(!generated.contains("bigint"));
    }

    #[test]
    fn checked_in_protocol_matches_rust_dtos() {
        let path =
            Path::new(env!("CARGO_MANIFEST_DIR")).join(TSX_TYPESCRIPT_PROTOCOL_RELATIVE_PATH);
        let checked_in = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!(
                "failed to read generated protocol {}: {error}",
                path.display()
            )
        });
        assert_eq!(checked_in, generate_tsx_typescript_protocol_v1().unwrap());
    }
}
