#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AriaComponent {
    Button,
    Label,
    Document,
    DocumentHead,
    DocumentBody,
    DocumentTitle,
    Metadata,
    ResourceLink,
    StyleSheet,
    Script,
    Template,
    Slot,
    Text,
    Abbreviation,
    Citation,
    Definition,
    DataValue,
    InsertedText,
    DeletedText,
    MarkedText,
    Time,
    Emphasis,
    StrongText,
    Code,
    KeyboardInput,
    SampleOutput,
    Variable,
    InlineQuote,
    Subscript,
    Superscript,
    SmallText,
    BoldText,
    ItalicText,
    StruckText,
    UnderlinedText,
    BidirectionalIsolate,
    BidirectionalOverride,
    Paragraph,
    PreformattedText,
    BlockQuote,
    ContactAddress,
    LineBreak,
    WordBreakOpportunity,
    NoBreakText,
    CenteredText,
    FontText,
    BigText,
    TeletypeText,
    Applet,
    BackgroundSound,
    Frame,
    FrameSet,
    NoEmbedFallback,
    NoFramesFallback,
    Marquee,
    Math,
    NextId,
    SelectedContent,
    Heading,
    HeadingGroup,
    Ruby,
    RubyBase,
    RubyText,
    RubyParenthesis,
    RubyTextContainer,
    Main,
    Navigation,
    Header,
    Footer,
    Article,
    Section,
    Aside,
    Search,
    Disclosure,
    DisclosureSummary,
    Figure,
    FigureCaption,
    DescriptionList,
    DescriptionTerm,
    DescriptionDetails,
    Image,
    Media,
    Canvas,
    EmbeddedContent,
    Link,
    ImageMap,
    ImageMapArea,
    TextField,
    Input,
    Checkbox,
    Switch,
    RadioGroup,
    Radio,
    FieldSet,
    Legend,
    OptionGroup,
    Output,
    Meter,
    Select,
    SelectValue,
    ListBox,
    ListBoxItem,
    Dialog,
    Popover,
    Tabs,
    TabList,
    Tab,
    TabPanel,
    Group,
    Form,
    Menu,
    MenuItem,
    Separator,
    Slider,
    ProgressBar,
    Toolbar,
    Table,
    TableSection,
    TableRow,
    TableCell,
    TableColumn,
    TableCaption,
}

impl AriaComponent {
    pub const fn as_str(self) -> &'static str {
        match self {
            AriaComponent::Button => "Button",
            AriaComponent::Label => "Label",
            AriaComponent::Document => "Document",
            AriaComponent::DocumentHead => "DocumentHead",
            AriaComponent::DocumentBody => "DocumentBody",
            AriaComponent::DocumentTitle => "DocumentTitle",
            AriaComponent::Metadata => "Metadata",
            AriaComponent::ResourceLink => "ResourceLink",
            AriaComponent::StyleSheet => "StyleSheet",
            AriaComponent::Script => "Script",
            AriaComponent::Template => "Template",
            AriaComponent::Slot => "Slot",
            AriaComponent::Text => "Text",
            AriaComponent::Abbreviation => "Abbreviation",
            AriaComponent::Citation => "Citation",
            AriaComponent::Definition => "Definition",
            AriaComponent::DataValue => "DataValue",
            AriaComponent::InsertedText => "InsertedText",
            AriaComponent::DeletedText => "DeletedText",
            AriaComponent::MarkedText => "MarkedText",
            AriaComponent::Time => "Time",
            AriaComponent::Emphasis => "Emphasis",
            AriaComponent::StrongText => "StrongText",
            AriaComponent::Code => "Code",
            AriaComponent::KeyboardInput => "KeyboardInput",
            AriaComponent::SampleOutput => "SampleOutput",
            AriaComponent::Variable => "Variable",
            AriaComponent::InlineQuote => "InlineQuote",
            AriaComponent::Subscript => "Subscript",
            AriaComponent::Superscript => "Superscript",
            AriaComponent::SmallText => "SmallText",
            AriaComponent::BoldText => "BoldText",
            AriaComponent::ItalicText => "ItalicText",
            AriaComponent::StruckText => "StruckText",
            AriaComponent::UnderlinedText => "UnderlinedText",
            AriaComponent::BidirectionalIsolate => "BidirectionalIsolate",
            AriaComponent::BidirectionalOverride => "BidirectionalOverride",
            AriaComponent::Paragraph => "Paragraph",
            AriaComponent::PreformattedText => "PreformattedText",
            AriaComponent::BlockQuote => "BlockQuote",
            AriaComponent::ContactAddress => "ContactAddress",
            AriaComponent::LineBreak => "LineBreak",
            AriaComponent::WordBreakOpportunity => "WordBreakOpportunity",
            AriaComponent::NoBreakText => "NoBreakText",
            AriaComponent::CenteredText => "CenteredText",
            AriaComponent::FontText => "FontText",
            AriaComponent::BigText => "BigText",
            AriaComponent::TeletypeText => "TeletypeText",
            AriaComponent::Applet => "Applet",
            AriaComponent::BackgroundSound => "BackgroundSound",
            AriaComponent::Frame => "Frame",
            AriaComponent::FrameSet => "FrameSet",
            AriaComponent::NoEmbedFallback => "NoEmbedFallback",
            AriaComponent::NoFramesFallback => "NoFramesFallback",
            AriaComponent::Marquee => "Marquee",
            AriaComponent::Math => "Math",
            AriaComponent::NextId => "NextId",
            AriaComponent::SelectedContent => "SelectedContent",
            AriaComponent::Heading => "Heading",
            AriaComponent::HeadingGroup => "HeadingGroup",
            AriaComponent::Ruby => "Ruby",
            AriaComponent::RubyBase => "RubyBase",
            AriaComponent::RubyText => "RubyText",
            AriaComponent::RubyParenthesis => "RubyParenthesis",
            AriaComponent::RubyTextContainer => "RubyTextContainer",
            AriaComponent::Main => "Main",
            AriaComponent::Navigation => "Navigation",
            AriaComponent::Header => "Header",
            AriaComponent::Footer => "Footer",
            AriaComponent::Article => "Article",
            AriaComponent::Section => "Section",
            AriaComponent::Aside => "Aside",
            AriaComponent::Search => "Search",
            AriaComponent::Disclosure => "Disclosure",
            AriaComponent::DisclosureSummary => "DisclosureSummary",
            AriaComponent::Figure => "Figure",
            AriaComponent::FigureCaption => "FigureCaption",
            AriaComponent::DescriptionList => "DescriptionList",
            AriaComponent::DescriptionTerm => "DescriptionTerm",
            AriaComponent::DescriptionDetails => "DescriptionDetails",
            AriaComponent::Image => "Image",
            AriaComponent::Media => "Media",
            AriaComponent::Canvas => "Canvas",
            AriaComponent::EmbeddedContent => "EmbeddedContent",
            AriaComponent::Link => "Link",
            AriaComponent::ImageMap => "ImageMap",
            AriaComponent::ImageMapArea => "ImageMapArea",
            AriaComponent::TextField => "TextField",
            AriaComponent::Input => "Input",
            AriaComponent::Checkbox => "Checkbox",
            AriaComponent::Switch => "Switch",
            AriaComponent::RadioGroup => "RadioGroup",
            AriaComponent::Radio => "Radio",
            AriaComponent::FieldSet => "FieldSet",
            AriaComponent::Legend => "Legend",
            AriaComponent::OptionGroup => "OptionGroup",
            AriaComponent::Output => "Output",
            AriaComponent::Meter => "Meter",
            AriaComponent::Select => "Select",
            AriaComponent::SelectValue => "SelectValue",
            AriaComponent::ListBox => "ListBox",
            AriaComponent::ListBoxItem => "ListBoxItem",
            AriaComponent::Dialog => "Dialog",
            AriaComponent::Popover => "Popover",
            AriaComponent::Tabs => "Tabs",
            AriaComponent::TabList => "TabList",
            AriaComponent::Tab => "Tab",
            AriaComponent::TabPanel => "TabPanel",
            AriaComponent::Group => "Group",
            AriaComponent::Form => "Form",
            AriaComponent::Menu => "Menu",
            AriaComponent::MenuItem => "MenuItem",
            AriaComponent::Separator => "Separator",
            AriaComponent::Slider => "Slider",
            AriaComponent::ProgressBar => "ProgressBar",
            AriaComponent::Toolbar => "Toolbar",
            AriaComponent::Table => "Table",
            AriaComponent::TableSection => "TableSection",
            AriaComponent::TableRow => "TableRow",
            AriaComponent::TableCell => "TableCell",
            AriaComponent::TableColumn => "TableColumn",
            AriaComponent::TableCaption => "TableCaption",
        }
    }
}
