#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SemanticComponent {
    Button,
    Label,
    Document,
    DocumentHead,
    DocumentBody,
    DocumentTitle,
    Metadata,
    ResourceLink,
    StyleSheet,
    Script,
    Template,
    Slot,
    Text,
    Abbreviation,
    Citation,
    Definition,
    DataValue,
    InsertedText,
    DeletedText,
    MarkedText,
    Time,
    Emphasis,
    StrongText,
    Code,
    KeyboardInput,
    SampleOutput,
    Variable,
    InlineQuote,
    Subscript,
    Superscript,
    SmallText,
    BoldText,
    ItalicText,
    StruckText,
    UnderlinedText,
    BidirectionalIsolate,
    BidirectionalOverride,
    Paragraph,
    PreformattedText,
    BlockQuote,
    ContactAddress,
    LineBreak,
    WordBreakOpportunity,
    NoBreakText,
    CenteredText,
    FontText,
    BigText,
    TeletypeText,
    Applet,
    BackgroundSound,
    Frame,
    FrameSet,
    NoEmbedFallback,
    NoFramesFallback,
    Marquee,
    Math,
    NextId,
    SelectedContent,
    Heading,
    HeadingGroup,
    Ruby,
    RubyBase,
    RubyText,
    RubyParenthesis,
    RubyTextContainer,
    Main,
    Navigation,
    Header,
    Footer,
    Article,
    Section,
    Aside,
    Search,
    Disclosure,
    DisclosureSummary,
    Figure,
    FigureCaption,
    DescriptionList,
    DescriptionTerm,
    DescriptionDetails,
    Image,
    Media,
    Canvas,
    EmbeddedContent,
    Link,
    ImageMap,
    ImageMapArea,
    TextField,
    Input,
    Checkbox,
    Switch,
    RadioGroup,
    Radio,
    FieldSet,
    Legend,
    OptionGroup,
    Output,
    Meter,
    ComboBox,
    Select,
    SelectValue,
    ListBox,
    ListBoxItem,
    Tree,
    TreeItem,
    Dialog,
    Popover,
    Tabs,
    TabList,
    Tab,
    TabPanel,
    Group,
    Form,
    Menu,
    MenuItem,
    Separator,
    Slider,
    ProgressBar,
    Toolbar,
    Table,
    TableSection,
    TableRow,
    TableCell,
    TableColumn,
    TableCaption,
}

impl SemanticComponent {
    pub const ALL: &'static [Self] = &[
        Self::Button,
        Self::Label,
        Self::Document,
        Self::DocumentHead,
        Self::DocumentBody,
        Self::DocumentTitle,
        Self::Metadata,
        Self::ResourceLink,
        Self::StyleSheet,
        Self::Script,
        Self::Template,
        Self::Slot,
        Self::Text,
        Self::Abbreviation,
        Self::Citation,
        Self::Definition,
        Self::DataValue,
        Self::InsertedText,
        Self::DeletedText,
        Self::MarkedText,
        Self::Time,
        Self::Emphasis,
        Self::StrongText,
        Self::Code,
        Self::KeyboardInput,
        Self::SampleOutput,
        Self::Variable,
        Self::InlineQuote,
        Self::Subscript,
        Self::Superscript,
        Self::SmallText,
        Self::BoldText,
        Self::ItalicText,
        Self::StruckText,
        Self::UnderlinedText,
        Self::BidirectionalIsolate,
        Self::BidirectionalOverride,
        Self::Paragraph,
        Self::PreformattedText,
        Self::BlockQuote,
        Self::ContactAddress,
        Self::LineBreak,
        Self::WordBreakOpportunity,
        Self::NoBreakText,
        Self::CenteredText,
        Self::FontText,
        Self::BigText,
        Self::TeletypeText,
        Self::Applet,
        Self::BackgroundSound,
        Self::Frame,
        Self::FrameSet,
        Self::NoEmbedFallback,
        Self::NoFramesFallback,
        Self::Marquee,
        Self::Math,
        Self::NextId,
        Self::SelectedContent,
        Self::Heading,
        Self::HeadingGroup,
        Self::Ruby,
        Self::RubyBase,
        Self::RubyText,
        Self::RubyParenthesis,
        Self::RubyTextContainer,
        Self::Main,
        Self::Navigation,
        Self::Header,
        Self::Footer,
        Self::Article,
        Self::Section,
        Self::Aside,
        Self::Search,
        Self::Disclosure,
        Self::DisclosureSummary,
        Self::Figure,
        Self::FigureCaption,
        Self::DescriptionList,
        Self::DescriptionTerm,
        Self::DescriptionDetails,
        Self::Image,
        Self::Media,
        Self::Canvas,
        Self::EmbeddedContent,
        Self::Link,
        Self::ImageMap,
        Self::ImageMapArea,
        Self::TextField,
        Self::Input,
        Self::Checkbox,
        Self::Switch,
        Self::RadioGroup,
        Self::Radio,
        Self::FieldSet,
        Self::Legend,
        Self::OptionGroup,
        Self::Output,
        Self::Meter,
        Self::ComboBox,
        Self::Select,
        Self::SelectValue,
        Self::ListBox,
        Self::ListBoxItem,
        Self::Tree,
        Self::TreeItem,
        Self::Dialog,
        Self::Popover,
        Self::Tabs,
        Self::TabList,
        Self::Tab,
        Self::TabPanel,
        Self::Group,
        Self::Form,
        Self::Menu,
        Self::MenuItem,
        Self::Separator,
        Self::Slider,
        Self::ProgressBar,
        Self::Toolbar,
        Self::Table,
        Self::TableSection,
        Self::TableRow,
        Self::TableCell,
        Self::TableColumn,
        Self::TableCaption,
    ];

    pub fn from_name(component: &str) -> Option<Self> {
        Self::ALL
            .iter()
            .copied()
            .find(|candidate| candidate.as_str() == component)
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            SemanticComponent::Button => "Button",
            SemanticComponent::Label => "Label",
            SemanticComponent::Document => "Document",
            SemanticComponent::DocumentHead => "DocumentHead",
            SemanticComponent::DocumentBody => "DocumentBody",
            SemanticComponent::DocumentTitle => "DocumentTitle",
            SemanticComponent::Metadata => "Metadata",
            SemanticComponent::ResourceLink => "ResourceLink",
            SemanticComponent::StyleSheet => "StyleSheet",
            SemanticComponent::Script => "Script",
            SemanticComponent::Template => "Template",
            SemanticComponent::Slot => "Slot",
            SemanticComponent::Text => "Text",
            SemanticComponent::Abbreviation => "Abbreviation",
            SemanticComponent::Citation => "Citation",
            SemanticComponent::Definition => "Definition",
            SemanticComponent::DataValue => "DataValue",
            SemanticComponent::InsertedText => "InsertedText",
            SemanticComponent::DeletedText => "DeletedText",
            SemanticComponent::MarkedText => "MarkedText",
            SemanticComponent::Time => "Time",
            SemanticComponent::Emphasis => "Emphasis",
            SemanticComponent::StrongText => "StrongText",
            SemanticComponent::Code => "Code",
            SemanticComponent::KeyboardInput => "KeyboardInput",
            SemanticComponent::SampleOutput => "SampleOutput",
            SemanticComponent::Variable => "Variable",
            SemanticComponent::InlineQuote => "InlineQuote",
            SemanticComponent::Subscript => "Subscript",
            SemanticComponent::Superscript => "Superscript",
            SemanticComponent::SmallText => "SmallText",
            SemanticComponent::BoldText => "BoldText",
            SemanticComponent::ItalicText => "ItalicText",
            SemanticComponent::StruckText => "StruckText",
            SemanticComponent::UnderlinedText => "UnderlinedText",
            SemanticComponent::BidirectionalIsolate => "BidirectionalIsolate",
            SemanticComponent::BidirectionalOverride => "BidirectionalOverride",
            SemanticComponent::Paragraph => "Paragraph",
            SemanticComponent::PreformattedText => "PreformattedText",
            SemanticComponent::BlockQuote => "BlockQuote",
            SemanticComponent::ContactAddress => "ContactAddress",
            SemanticComponent::LineBreak => "LineBreak",
            SemanticComponent::WordBreakOpportunity => "WordBreakOpportunity",
            SemanticComponent::NoBreakText => "NoBreakText",
            SemanticComponent::CenteredText => "CenteredText",
            SemanticComponent::FontText => "FontText",
            SemanticComponent::BigText => "BigText",
            SemanticComponent::TeletypeText => "TeletypeText",
            SemanticComponent::Applet => "Applet",
            SemanticComponent::BackgroundSound => "BackgroundSound",
            SemanticComponent::Frame => "Frame",
            SemanticComponent::FrameSet => "FrameSet",
            SemanticComponent::NoEmbedFallback => "NoEmbedFallback",
            SemanticComponent::NoFramesFallback => "NoFramesFallback",
            SemanticComponent::Marquee => "Marquee",
            SemanticComponent::Math => "Math",
            SemanticComponent::NextId => "NextId",
            SemanticComponent::SelectedContent => "SelectedContent",
            SemanticComponent::Heading => "Heading",
            SemanticComponent::HeadingGroup => "HeadingGroup",
            SemanticComponent::Ruby => "Ruby",
            SemanticComponent::RubyBase => "RubyBase",
            SemanticComponent::RubyText => "RubyText",
            SemanticComponent::RubyParenthesis => "RubyParenthesis",
            SemanticComponent::RubyTextContainer => "RubyTextContainer",
            SemanticComponent::Main => "Main",
            SemanticComponent::Navigation => "Navigation",
            SemanticComponent::Header => "Header",
            SemanticComponent::Footer => "Footer",
            SemanticComponent::Article => "Article",
            SemanticComponent::Section => "Section",
            SemanticComponent::Aside => "Aside",
            SemanticComponent::Search => "Search",
            SemanticComponent::Disclosure => "Disclosure",
            SemanticComponent::DisclosureSummary => "DisclosureSummary",
            SemanticComponent::Figure => "Figure",
            SemanticComponent::FigureCaption => "FigureCaption",
            SemanticComponent::DescriptionList => "DescriptionList",
            SemanticComponent::DescriptionTerm => "DescriptionTerm",
            SemanticComponent::DescriptionDetails => "DescriptionDetails",
            SemanticComponent::Image => "Image",
            SemanticComponent::Media => "Media",
            SemanticComponent::Canvas => "Canvas",
            SemanticComponent::EmbeddedContent => "EmbeddedContent",
            SemanticComponent::Link => "Link",
            SemanticComponent::ImageMap => "ImageMap",
            SemanticComponent::ImageMapArea => "ImageMapArea",
            SemanticComponent::TextField => "TextField",
            SemanticComponent::Input => "Input",
            SemanticComponent::Checkbox => "Checkbox",
            SemanticComponent::Switch => "Switch",
            SemanticComponent::RadioGroup => "RadioGroup",
            SemanticComponent::Radio => "Radio",
            SemanticComponent::FieldSet => "FieldSet",
            SemanticComponent::Legend => "Legend",
            SemanticComponent::OptionGroup => "OptionGroup",
            SemanticComponent::Output => "Output",
            SemanticComponent::Meter => "Meter",
            SemanticComponent::ComboBox => "ComboBox",
            SemanticComponent::Select => "Select",
            SemanticComponent::SelectValue => "SelectValue",
            SemanticComponent::ListBox => "ListBox",
            SemanticComponent::ListBoxItem => "ListBoxItem",
            SemanticComponent::Tree => "Tree",
            SemanticComponent::TreeItem => "TreeItem",
            SemanticComponent::Dialog => "Dialog",
            SemanticComponent::Popover => "Popover",
            SemanticComponent::Tabs => "Tabs",
            SemanticComponent::TabList => "TabList",
            SemanticComponent::Tab => "Tab",
            SemanticComponent::TabPanel => "TabPanel",
            SemanticComponent::Group => "Group",
            SemanticComponent::Form => "Form",
            SemanticComponent::Menu => "Menu",
            SemanticComponent::MenuItem => "MenuItem",
            SemanticComponent::Separator => "Separator",
            SemanticComponent::Slider => "Slider",
            SemanticComponent::ProgressBar => "ProgressBar",
            SemanticComponent::Toolbar => "Toolbar",
            SemanticComponent::Table => "Table",
            SemanticComponent::TableSection => "TableSection",
            SemanticComponent::TableRow => "TableRow",
            SemanticComponent::TableCell => "TableCell",
            SemanticComponent::TableColumn => "TableColumn",
            SemanticComponent::TableCaption => "TableCaption",
        }
    }
}
