mod classes;
mod components;
mod variants;

pub use classes::{
    UI_BADGE_BASE_CLASS, UI_BADGE_CLASS, UI_BUTTON_BASE_CLASS, UI_BUTTON_CLASS,
    UI_BUTTON_DEFAULT_SIZE_CLASS, UI_BUTTON_DEFAULT_VARIANT_CLASS, UI_CARD_CLASS,
    UI_CARD_CONTENT_CLASS, UI_CARD_DESCRIPTION_CLASS, UI_CARD_FOOTER_CLASS, UI_CARD_HEADER_CLASS,
    UI_CARD_TITLE_CLASS, UI_FIELD_CONTROL_CLASS, UI_FIELD_CONTROL_INPUT_CLASS,
    UI_FIELD_CONTROL_TRIGGER_CLASS, UI_INPUT_CLASS, UI_SEPARATOR_CLASS, UI_TABS_CLASS,
    UI_TABS_CONTENT_CLASS, UI_TABS_LIST_CLASS, UI_TABS_TRIGGER_CLASS, UI_TEXTAREA_CLASS,
};
pub use components::builtin_component_registry;
pub use components::{
    ui_article, ui_aside, ui_autocomplete, ui_badge, ui_breadcrumb, ui_breadcrumbs, ui_button,
    ui_calendar, ui_calendar_cell, ui_calendar_grid, ui_calendar_grid_body,
    ui_calendar_grid_header, ui_calendar_header_cell, ui_calendar_heading,
    ui_calendar_month_picker, ui_calendar_year_picker, ui_card, ui_card_content,
    ui_card_description, ui_card_footer, ui_card_header, ui_card_title, ui_checkbox,
    ui_checkbox_group, ui_clipboard_target, ui_collection, ui_color_area, ui_color_field,
    ui_color_picker, ui_color_slider, ui_color_swatch, ui_color_swatch_picker,
    ui_color_swatch_picker_item, ui_color_thumb, ui_color_wheel, ui_color_wheel_track,
    ui_column_resizer, ui_combo_box, ui_combo_box_value, ui_date_field, ui_date_input,
    ui_date_picker, ui_date_range_picker, ui_date_segment, ui_description, ui_dialog,
    ui_dialog_trigger, ui_disclosure, ui_disclosure_group, ui_disclosure_panel,
    ui_disclosure_summary, ui_draggable, ui_drop_indicator, ui_drop_zone, ui_droppable,
    ui_field_error, ui_field_set, ui_file_trigger, ui_focus_ring, ui_focus_scope, ui_focus_within,
    ui_focusable, ui_footer, ui_form, ui_grid_list, ui_grid_list_header, ui_grid_list_item,
    ui_grid_list_load_more_item, ui_grid_list_section, ui_group, ui_header, ui_heading,
    ui_hoverable, ui_i18n_provider, ui_input, ui_keyboard, ui_keyboard_target, ui_label, ui_legend,
    ui_link, ui_list_box, ui_list_box_header, ui_list_box_item, ui_list_box_load_more_item,
    ui_list_box_section, ui_long_pressable, ui_main, ui_menu, ui_menu_item, ui_menu_section,
    ui_menu_trigger, ui_meter, ui_modal, ui_modal_overlay, ui_movable, ui_nav_link,
    ui_navigate_button, ui_navigation, ui_number_field, ui_overlay_arrow, ui_popover, ui_pressable,
    ui_progress_bar, ui_radio, ui_radio_group, ui_range_calendar, ui_resizable_table_container,
    ui_route, ui_router, ui_routes, ui_search, ui_search_field, ui_section, ui_select,
    ui_select_value, ui_selection_indicator, ui_separator, ui_shared_element,
    ui_shared_element_transition, ui_slider, ui_slider_fill, ui_slider_output, ui_slider_thumb,
    ui_slider_track, ui_submenu_trigger, ui_switch, ui_tab_panels, ui_table, ui_table_body,
    ui_table_caption, ui_table_cell, ui_table_column, ui_table_footer, ui_table_header,
    ui_table_load_more_item, ui_table_row, ui_tabs, ui_tabs_content, ui_tabs_list, ui_tabs_trigger,
    ui_tag, ui_tag_group, ui_tag_list, ui_text, ui_text_field, ui_textarea, ui_time_field,
    ui_toast, ui_toast_region, ui_toggle_button, ui_toggle_button_group, ui_toolbar, ui_tooltip,
    ui_tooltip_trigger, ui_tree, ui_tree_header, ui_tree_item, ui_tree_item_content,
    ui_tree_load_more_item, ui_tree_section, ui_virtualizer, ui_visually_hidden, UiArticleProps,
    UiAsideProps, UiAutocompleteProps, UiBadgeProps, UiBreadcrumbProps, UiBreadcrumbsProps,
    UiButtonProps, UiCalendarCellProps, UiCalendarGridBodyProps, UiCalendarGridHeaderProps,
    UiCalendarGridProps, UiCalendarHeaderCellProps, UiCalendarHeadingProps,
    UiCalendarMonthPickerProps, UiCalendarProps, UiCalendarYearPickerProps, UiCardContentProps,
    UiCardDescriptionProps, UiCardFooterProps, UiCardHeaderProps, UiCardProps, UiCardTitleProps,
    UiCheckboxGroupProps, UiCheckboxProps, UiClipboardTargetProps, UiCollectionProps,
    UiColorAreaProps, UiColorFieldProps, UiColorPickerProps, UiColorSliderProps,
    UiColorSwatchPickerItemProps, UiColorSwatchPickerProps, UiColorSwatchProps, UiColorThumbProps,
    UiColorWheelProps, UiColorWheelTrackProps, UiColumnResizerProps, UiComboBoxProps,
    UiComboBoxValueProps, UiDateFieldProps, UiDateInputProps, UiDatePickerProps,
    UiDateRangePickerProps, UiDateSegmentProps, UiDescriptionProps, UiDialogProps,
    UiDialogTriggerProps, UiDisclosureGroupProps, UiDisclosurePanelProps, UiDisclosureProps,
    UiDisclosureSummaryProps, UiDraggableProps, UiDropIndicatorProps, UiDropZoneProps,
    UiDroppableProps, UiFieldErrorProps, UiFieldSetProps, UiFileTriggerProps, UiFocusRingProps,
    UiFocusScopeProps, UiFocusWithinProps, UiFocusableProps, UiFooterProps, UiFormProps,
    UiGridListHeaderProps, UiGridListItemProps, UiGridListLoadMoreItemProps, UiGridListProps,
    UiGridListSectionProps, UiGroupProps, UiHeaderProps, UiHeadingProps, UiHoverableProps,
    UiI18nProviderProps, UiInputProps, UiKeyboardProps, UiKeyboardTargetProps, UiLabelProps,
    UiLegendProps, UiLinkProps, UiListBoxHeaderProps, UiListBoxItemProps,
    UiListBoxLoadMoreItemProps, UiListBoxProps, UiListBoxSectionProps, UiLongPressableProps,
    UiMainProps, UiMenuItemProps, UiMenuProps, UiMenuSectionProps, UiMenuTriggerProps,
    UiMeterProps, UiModalOverlayProps, UiModalProps, UiMovableProps, UiNavLinkProps,
    UiNavigateButtonProps, UiNavigationProps, UiNumberFieldProps, UiOverlayArrowProps,
    UiPopoverProps, UiPressableProps, UiProgressBarProps, UiRadioGroupProps, UiRadioProps,
    UiRangeCalendarProps, UiResizableTableContainerProps, UiRouteProps, UiRouterProps,
    UiRoutesProps, UiSearchFieldProps, UiSearchProps, UiSectionProps, UiSelectProps,
    UiSelectValueProps, UiSelectionIndicatorProps, UiSeparatorProps, UiSharedElementProps,
    UiSharedElementTransitionProps, UiSliderFillProps, UiSliderOutputProps, UiSliderProps,
    UiSliderThumbProps, UiSliderTrackProps, UiSubmenuTriggerProps, UiSwitchProps, UiTabPanelsProps,
    UiTableBodyProps, UiTableCaptionProps, UiTableCellProps, UiTableColumnProps,
    UiTableFooterProps, UiTableHeaderProps, UiTableLoadMoreItemProps, UiTableProps,
    UiTableRowProps, UiTabsContentProps, UiTabsListProps, UiTabsProps, UiTabsTriggerProps,
    UiTagGroupProps, UiTagListProps, UiTagProps, UiTextFieldProps, UiTextProps, UiTextareaProps,
    UiTimeFieldProps, UiToastProps, UiToastRegionProps, UiToggleButtonGroupProps,
    UiToggleButtonProps, UiToolbarProps, UiTooltipProps, UiTooltipTriggerProps, UiTreeHeaderProps,
    UiTreeItemContentProps, UiTreeItemProps, UiTreeLoadMoreItemProps, UiTreeProps,
    UiTreeSectionProps, UiVirtualizerProps, UiVisuallyHiddenProps,
};
pub use variants::{ui_badge_variants, ui_button_variants};

#[cfg(test)]
mod interaction_tests;
#[cfg(test)]
mod selection_tests;
#[cfg(test)]
mod tests;
