import type {ActionLike, CompiledJsxElement, CompiledJsxNode} from './index.js';

export const Fragment: unique symbol;

export type StyleValue = string | number | boolean | null | undefined;

export interface WebCompatibleProps {
  key?: string | number;
  id?: string;
  title?: string;
  hidden?: boolean | string;
  is?: string;
  lang?: string;
  dir?: 'ltr' | 'rtl' | 'auto' | string;
  tabIndex?: number | string;
  tabindex?: number | string;
  role?: string;
  'aria-labelledby'?: string;
  'aria-describedby'?: string;
  'aria-details'?: string;
  'aria-controls'?: string;
  'aria-owns'?: string;
  'aria-flowto'?: string;
  'aria-errormessage'?: string;
  'aria-activedescendant'?: string;
  'aria-description'?: string;
  'aria-roledescription'?: string;
  'aria-keyshortcuts'?: string;
  'aria-valuetext'?: string;
  'aria-level'?: number | string;
  'aria-posinset'?: number | string;
  'aria-setsize'?: number | string;
  'aria-rowcount'?: number | string;
  'aria-rowindex'?: number | string;
  'aria-rowspan'?: number | string;
  'aria-colcount'?: number | string;
  'aria-colindex'?: number | string;
  'aria-colspan'?: number | string;
  'aria-rowindextext'?: string;
  'aria-colindextext'?: string;
  'aria-sort'?: 'ascending' | 'descending' | 'none' | 'other' | string;
  'aria-hidden'?: boolean | string;
  'aria-autocomplete'?: 'inline' | 'list' | 'both' | 'none' | string;
  'aria-multiline'?: boolean | string;
  'aria-current'?: boolean | 'page' | 'step' | 'location' | 'date' | 'time' | string;
  'aria-haspopup'?: boolean | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog' | string;
  'aria-pressed'?: boolean | 'mixed' | string;
  'aria-live'?: 'off' | 'polite' | 'assertive' | string;
  'aria-atomic'?: boolean | string;
  'aria-busy'?: boolean | string;
  'aria-relevant'?: string;
  'aria-modal'?: boolean | string;
  accessKey?: string;
  accesskey?: string;
  contentEditable?: boolean | 'true' | 'false' | 'plaintext-only' | string;
  contenteditable?: boolean | 'true' | 'false' | 'plaintext-only' | string;
  draggable?: boolean | 'true' | 'false' | 'auto' | string;
  spellCheck?: boolean | 'true' | 'false' | string;
  spellcheck?: boolean | 'true' | 'false' | string;
  translate?: boolean | 'yes' | 'no' | string;
  inert?: boolean | string;
  popover?: boolean | 'auto' | 'manual' | string;
  anchor?: string;
  open?: boolean | string;
  slot?: string;
  part?: string;
  exportParts?: string;
  exportparts?: string;
  itemScope?: boolean | string;
  itemscope?: boolean | string;
  itemProp?: string;
  itemprop?: string;
  itemType?: string;
  itemtype?: string;
  itemID?: string;
  itemid?: string;
  itemRef?: string;
  itemref?: string;
  command?: string;
  commandFor?: string;
  commandfor?: string;
  popoverTarget?: string;
  popovertarget?: string;
  popoverTargetAction?: 'hide' | 'show' | 'toggle' | string;
  popovertargetaction?: 'hide' | 'show' | 'toggle' | string;
  name?: string;
  htmlFor?: string;
  'for'?: string;
  href?: string;
  cite?: string;
  dateTime?: string;
  datetime?: string;
  src?: string;
  srcSet?: string;
  srcset?: string;
  sizes?: string;
  media?: string;
  type?: string;
  download?: boolean | string;
  ping?: string;
  rel?: string;
  hrefLang?: string;
  hreflang?: string;
  as?: string;
  integrity?: string;
  blocking?: string;
  nonce?: string;
  imageSrcSet?: string;
  imagesrcset?: string;
  imageSizes?: string;
  imagesizes?: string;
  async?: boolean;
  defer?: boolean;
  noModule?: boolean;
  nomodule?: boolean;
  allow?: string;
  allowFullScreen?: boolean;
  allowfullscreen?: boolean;
  sandbox?: boolean | string;
  srcDoc?: string;
  srcdoc?: string;
  form?: string;
  width?: number | string;
  height?: number | string;
  className?: string;
  style?: Record<string, StyleValue> | string;
  children?: unknown;
  disabled?: boolean;
  required?: boolean;
  readOnly?: boolean;
  multiple?: boolean;
  autoFocus?: boolean;
  invalid?: boolean;
  selected?: boolean;
  checked?: boolean;
  defaultChecked?: boolean;
  expanded?: boolean;
  onClick?: ActionLike;
  onPress?: ActionLike;
  onChange?: ActionLike;
  onSelectionChange?: ActionLike;
  onFocus?: ActionLike;
  onBlur?: ActionLike;
  onFocusChange?: ActionLike;
  onToggle?: ActionLike;
  onExpandedChange?: ActionLike;
  onKeyDown?: ActionLike;
  onKeyUp?: ActionLike;
  isDisabled?: boolean;
  isRequired?: boolean;
  isInvalid?: boolean;
  isReadOnly?: boolean;
  isSelected?: boolean;
  isChecked?: boolean;
  isExpanded?: boolean;
  textValue?: string;
  value?: string | number | boolean;
  defaultValue?: string | number | boolean;
  placeholder?: string;
  autocomplete?: string;
  autoComplete?: string;
  inputMode?: string;
  enterKeyHint?: 'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send' | string;
  enterkeyhint?: 'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send' | string;
  autoCapitalize?: 'none' | 'off' | 'sentences' | 'words' | 'characters' | string;
  autocapitalize?: 'none' | 'off' | 'sentences' | 'words' | 'characters' | string;
  autoCorrect?: 'on' | 'off' | string;
  autocorrect?: 'on' | 'off' | string;
  virtualKeyboardPolicy?: 'auto' | 'manual' | string;
  virtualkeyboardpolicy?: 'auto' | 'manual' | string;
  accept?: string;
  capture?: boolean | string;
  alt?: string;
  loading?: string;
  decoding?: string;
  fetchPriority?: string;
  fetchpriority?: string;
  crossOrigin?: string;
  crossorigin?: string;
  referrerPolicy?: string;
  referrerpolicy?: string;
  poster?: string;
  controls?: boolean;
  autoPlay?: boolean;
  autoplay?: boolean;
  loop?: boolean;
  muted?: boolean;
  playsInline?: boolean;
  playsinline?: boolean;
  preload?: string;
  kind?: string;
  srcLang?: string;
  srclang?: string;
  label?: string;
  default?: boolean;
  list?: string;
  dirname?: string;
  action?: string;
  method?: string;
  encType?: string;
  enctype?: string;
  target?: string;
  noValidate?: boolean;
  formAction?: string;
  formEncType?: string;
  formMethod?: string;
  formTarget?: string;
  formNoValidate?: boolean;
  pattern?: string;
  minLength?: number | string;
  maxLength?: number | string;
  rows?: number | string;
  cols?: number | string;
  size?: number | string;
  colSpan?: number | string;
  colspan?: number | string;
  rowSpan?: number | string;
  rowspan?: number | string;
  headers?: string;
  scope?: string;
  abbr?: string;
  span?: number | string;
  start?: number | string;
  reversed?: boolean;
  orientation?: 'horizontal' | 'vertical';
  min?: number | string;
  max?: number | string;
  step?: number | string;
  low?: number | string;
  high?: number | string;
  optimum?: number | string;
  minValue?: number;
  maxValue?: number;
  valueNumber?: number;
  stepValue?: number;
  [attribute: `aria-${string}`]: StyleValue;
  [attribute: `data-${string}`]: StyleValue;
  [attribute: string]: unknown;
}

export type ComponentMarker<P extends WebCompatibleProps = WebCompatibleProps> = {
  readonly name: string;
  (props: P): never;
};

export function createComponent<P extends WebCompatibleProps = WebCompatibleProps>(
  name: string,
): ComponentMarker<P>;

export const Button: ComponentMarker;
export const Label: ComponentMarker;
export const Text: ComponentMarker;
export const TextField: ComponentMarker;
export const Input: ComponentMarker;
export const Checkbox: ComponentMarker;
export const Switch: ComponentMarker;
export const RadioGroup: ComponentMarker;
export const Radio: ComponentMarker;
export const Select: ComponentMarker;
export const SelectValue: ComponentMarker;
export const ListBox: ComponentMarker;
export const ListBoxItem: ComponentMarker;
export const Dialog: ComponentMarker;
export const Popover: ComponentMarker;
export const Tabs: ComponentMarker;
export const TabList: ComponentMarker;
export const Tab: ComponentMarker;
export const TabPanel: ComponentMarker;
export const Group: ComponentMarker;
export const Form: ComponentMarker;
export const Menu: ComponentMarker;
export const MenuItem: ComponentMarker;
export const Separator: ComponentMarker;
export const Slider: ComponentMarker;
export const ProgressBar: ComponentMarker;
export const Toolbar: ComponentMarker;
export const Link: ComponentMarker;

export function jsx(
  type: typeof Fragment,
  props: WebCompatibleProps,
  key?: unknown,
): CompiledJsxNode[];
export function jsx(
  type: string | ComponentMarker,
  props: WebCompatibleProps,
  key?: unknown,
): CompiledJsxElement;
export const jsxs: typeof jsx;

export namespace JSX {
  type Element = CompiledJsxElement | CompiledJsxNode[];
  interface ElementChildrenAttribute {
    children: {};
  }
  interface IntrinsicElements {
    [elementName: string]: WebCompatibleProps;
  }
}
