import type {ActionLike, CompiledJsxElement, CompiledJsxNode} from './index.js';

export const Fragment: unique symbol;

export type StyleValue = string | number | boolean | null | undefined;
export type Booleanish = boolean | string;

export interface WebCompatibleProps {
  key?: string | number;
  id?: string;
  title?: string;
  hidden?: boolean | string;
  is?: string;
  lang?: string;
  dir?: 'ltr' | 'rtl' | 'auto' | string;
  tabIndex?: number | string;
  tabindex?: number | string;
  role?: string;
  'aria-labelledby'?: string;
  'aria-describedby'?: string;
  'aria-details'?: string;
  'aria-controls'?: string;
  'aria-owns'?: string;
  'aria-flowto'?: string;
  'aria-errormessage'?: string;
  'aria-activedescendant'?: string;
  'aria-description'?: string;
  'aria-roledescription'?: string;
  'aria-keyshortcuts'?: string;
  'aria-valuetext'?: string;
  'aria-level'?: number | string;
  'aria-posinset'?: number | string;
  'aria-setsize'?: number | string;
  'aria-rowcount'?: number | string;
  'aria-rowindex'?: number | string;
  'aria-rowspan'?: number | string;
  'aria-colcount'?: number | string;
  'aria-colindex'?: number | string;
  'aria-colspan'?: number | string;
  'aria-rowindextext'?: string;
  'aria-colindextext'?: string;
  'aria-sort'?: 'ascending' | 'descending' | 'none' | 'other' | string;
  'aria-hidden'?: boolean | string;
  'aria-autocomplete'?: 'inline' | 'list' | 'both' | 'none' | string;
  'aria-multiline'?: boolean | string;
  'aria-current'?: boolean | 'page' | 'step' | 'location' | 'date' | 'time' | string;
  'aria-haspopup'?: boolean | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog' | string;
  'aria-pressed'?: boolean | 'mixed' | string;
  'aria-live'?: 'off' | 'polite' | 'assertive' | string;
  'aria-atomic'?: boolean | string;
  'aria-busy'?: boolean | string;
  'aria-relevant'?: string;
  'aria-modal'?: boolean | string;
  accessKey?: string;
  accesskey?: string;
  contentEditable?: boolean | 'true' | 'false' | 'plaintext-only' | string;
  contenteditable?: boolean | 'true' | 'false' | 'plaintext-only' | string;
  draggable?: boolean | 'true' | 'false' | 'auto' | string;
  spellCheck?: boolean | 'true' | 'false' | string;
  spellcheck?: boolean | 'true' | 'false' | string;
  translate?: boolean | 'yes' | 'no' | string;
  inert?: boolean | string;
  popover?: boolean | 'auto' | 'manual' | string;
  anchor?: string;
  open?: boolean | string;
  slot?: string;
  part?: string;
  exportParts?: string;
  exportparts?: string;
  itemScope?: boolean | string;
  itemscope?: boolean | string;
  itemProp?: string;
  itemprop?: string;
  itemType?: string;
  itemtype?: string;
  itemID?: string;
  itemid?: string;
  itemRef?: string;
  itemref?: string;
  command?: string;
  commandFor?: string;
  commandfor?: string;
  popoverTarget?: string;
  popovertarget?: string;
  popoverTargetAction?: 'hide' | 'show' | 'toggle' | string;
  popovertargetaction?: 'hide' | 'show' | 'toggle' | string;
  name?: string;
  htmlFor?: string;
  'for'?: string;
  href?: string;
  cite?: string;
  dateTime?: string;
  datetime?: string;
  src?: string;
  srcSet?: string;
  srcset?: string;
  sizes?: string;
  media?: string;
  type?: string;
  download?: boolean | string;
  ping?: string;
  rel?: string;
  hrefLang?: string;
  hreflang?: string;
  as?: string;
  integrity?: string;
  blocking?: string;
  nonce?: string;
  imageSrcSet?: string;
  imagesrcset?: string;
  imageSizes?: string;
  imagesizes?: string;
  async?: Booleanish;
  defer?: Booleanish;
  noModule?: Booleanish;
  nomodule?: Booleanish;
  allow?: string;
  allowFullScreen?: Booleanish;
  allowfullscreen?: Booleanish;
  sandbox?: boolean | string;
  srcDoc?: string;
  srcdoc?: string;
  form?: string;
  width?: number | string;
  height?: number | string;
  className?: string;
  style?: Record<string, StyleValue> | string;
  children?: unknown;
  disabled?: Booleanish;
  required?: Booleanish;
  readOnly?: Booleanish;
  multiple?: Booleanish;
  autoFocus?: Booleanish;
  invalid?: Booleanish;
  selected?: Booleanish;
  checked?: Booleanish;
  defaultChecked?: Booleanish;
  expanded?: Booleanish;
  onClick?: ActionLike;
  onPress?: ActionLike;
  onChange?: ActionLike;
  onInput?: ActionLike;
  onSelectionChange?: ActionLike;
  onFocus?: ActionLike;
  onBlur?: ActionLike;
  onFocusChange?: ActionLike;
  onToggle?: ActionLike;
  onExpandedChange?: ActionLike;
  onKeyDown?: ActionLike;
  onKeyUp?: ActionLike;
  isDisabled?: Booleanish;
  isRequired?: Booleanish;
  isInvalid?: Booleanish;
  isReadOnly?: Booleanish;
  isSelected?: Booleanish;
  isChecked?: Booleanish;
  isExpanded?: Booleanish;
  textValue?: string;
  value?: string | number | boolean;
  defaultValue?: string | number | boolean;
  placeholder?: string;
  autocomplete?: string;
  autoComplete?: string;
  inputMode?: string;
  enterKeyHint?: 'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send' | string;
  enterkeyhint?: 'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send' | string;
  autoCapitalize?: 'none' | 'off' | 'sentences' | 'words' | 'characters' | string;
  autocapitalize?: 'none' | 'off' | 'sentences' | 'words' | 'characters' | string;
  autoCorrect?: 'on' | 'off' | string;
  autocorrect?: 'on' | 'off' | string;
  virtualKeyboardPolicy?: 'auto' | 'manual' | string;
  virtualkeyboardpolicy?: 'auto' | 'manual' | string;
  accept?: string;
  capture?: boolean | string;
  alt?: string;
  loading?: string;
  decoding?: string;
  fetchPriority?: string;
  fetchpriority?: string;
  crossOrigin?: string;
  crossorigin?: string;
  referrerPolicy?: string;
  referrerpolicy?: string;
  poster?: string;
  controls?: Booleanish;
  autoPlay?: Booleanish;
  autoplay?: Booleanish;
  loop?: Booleanish;
  muted?: Booleanish;
  playsInline?: Booleanish;
  playsinline?: Booleanish;
  preload?: string;
  kind?: string;
  srcLang?: string;
  srclang?: string;
  label?: string;
  default?: Booleanish;
  list?: string;
  dirname?: string;
  action?: string;
  method?: string;
  encType?: string;
  enctype?: string;
  target?: string;
  noValidate?: Booleanish;
  formAction?: string;
  formEncType?: string;
  formMethod?: string;
  formTarget?: string;
  formNoValidate?: Booleanish;
  pattern?: string;
  minLength?: number | string;
  maxLength?: number | string;
  rows?: number | string;
  cols?: number | string;
  size?: number | string;
  colSpan?: number | string;
  colspan?: number | string;
  rowSpan?: number | string;
  rowspan?: number | string;
  headers?: string;
  scope?: string;
  abbr?: string;
  span?: number | string;
  start?: number | string;
  reversed?: Booleanish;
  orientation?: 'horizontal' | 'vertical';
  min?: number | string;
  max?: number | string;
  step?: number | string;
  low?: number | string;
  high?: number | string;
  optimum?: number | string;
  minValue?: number;
  maxValue?: number;
  valueNumber?: number;
  stepValue?: number;
  [attribute: `aria-${string}`]: StyleValue;
  [attribute: `data-${string}`]: StyleValue;
  [attribute: string]: unknown;
}

export type ComponentMarker<P extends WebCompatibleProps = WebCompatibleProps> = {
  readonly name: string;
  (props: P): never;
};

export function createComponent<P extends WebCompatibleProps = WebCompatibleProps>(
  name: string,
): ComponentMarker<P>;

export const Button: ComponentMarker;
export const Label: ComponentMarker;
export const Document: ComponentMarker;
export const DocumentHead: ComponentMarker;
export const DocumentBody: ComponentMarker;
export const DocumentTitle: ComponentMarker;
export const Metadata: ComponentMarker;
export const ResourceLink: ComponentMarker;
export const StyleSheet: ComponentMarker;
export const Script: ComponentMarker;
export const Template: ComponentMarker;
export const Slot: ComponentMarker;
export const Text: ComponentMarker;
export const Abbreviation: ComponentMarker;
export const Citation: ComponentMarker;
export const Definition: ComponentMarker;
export const DataValue: ComponentMarker;
export const InsertedText: ComponentMarker;
export const DeletedText: ComponentMarker;
export const MarkedText: ComponentMarker;
export const Time: ComponentMarker;
export const Emphasis: ComponentMarker;
export const StrongText: ComponentMarker;
export const Code: ComponentMarker;
export const KeyboardInput: ComponentMarker;
export const SampleOutput: ComponentMarker;
export const Variable: ComponentMarker;
export const InlineQuote: ComponentMarker;
export const Subscript: ComponentMarker;
export const Superscript: ComponentMarker;
export const SmallText: ComponentMarker;
export const BoldText: ComponentMarker;
export const ItalicText: ComponentMarker;
export const StruckText: ComponentMarker;
export const UnderlinedText: ComponentMarker;
export const BidirectionalIsolate: ComponentMarker;
export const BidirectionalOverride: ComponentMarker;
export const Paragraph: ComponentMarker;
export const PreformattedText: ComponentMarker;
export const BlockQuote: ComponentMarker;
export const ContactAddress: ComponentMarker;
export const LineBreak: ComponentMarker;
export const WordBreakOpportunity: ComponentMarker;
export const NoBreakText: ComponentMarker;
export const CenteredText: ComponentMarker;
export const FontText: ComponentMarker;
export const BigText: ComponentMarker;
export const TeletypeText: ComponentMarker;
export const Applet: ComponentMarker;
export const BackgroundSound: ComponentMarker;
export const Frame: ComponentMarker;
export const FrameSet: ComponentMarker;
export const NoEmbedFallback: ComponentMarker;
export const NoFramesFallback: ComponentMarker;
export const Marquee: ComponentMarker;
export const Math: ComponentMarker;
export const NextId: ComponentMarker;
export const SelectedContent: ComponentMarker;
export const Heading: ComponentMarker;
export const HeadingGroup: ComponentMarker;
export const Ruby: ComponentMarker;
export const RubyBase: ComponentMarker;
export const RubyText: ComponentMarker;
export const RubyParenthesis: ComponentMarker;
export const RubyTextContainer: ComponentMarker;
export const Main: ComponentMarker;
export const Navigation: ComponentMarker;
export const Header: ComponentMarker;
export const Footer: ComponentMarker;
export const Article: ComponentMarker;
export const Section: ComponentMarker;
export const Aside: ComponentMarker;
export const Search: ComponentMarker;
export const Disclosure: ComponentMarker;
export const DisclosureSummary: ComponentMarker;
export const Figure: ComponentMarker;
export const FigureCaption: ComponentMarker;
export const DescriptionList: ComponentMarker;
export const DescriptionTerm: ComponentMarker;
export const DescriptionDetails: ComponentMarker;
export const Image: ComponentMarker;
export const Media: ComponentMarker;
export const Canvas: ComponentMarker;
export const EmbeddedContent: ComponentMarker;
export const Link: ComponentMarker;
export const ImageMap: ComponentMarker;
export const ImageMapArea: ComponentMarker;
export const TextField: ComponentMarker;
export const Input: ComponentMarker;
export const Checkbox: ComponentMarker;
export const Switch: ComponentMarker;
export const RadioGroup: ComponentMarker;
export const Radio: ComponentMarker;
export const FieldSet: ComponentMarker;
export const Legend: ComponentMarker;
export const OptionGroup: ComponentMarker;
export const Output: ComponentMarker;
export const Meter: ComponentMarker;
export const Select: ComponentMarker;
export const SelectValue: ComponentMarker;
export const ListBox: ComponentMarker;
export const ListBoxItem: ComponentMarker;
export const Dialog: ComponentMarker;
export const Popover: ComponentMarker;
export const Tabs: ComponentMarker;
export const TabList: ComponentMarker;
export const Tab: ComponentMarker;
export const TabPanel: ComponentMarker;
export const Group: ComponentMarker;
export const Form: ComponentMarker;
export const Menu: ComponentMarker;
export const MenuItem: ComponentMarker;
export const Separator: ComponentMarker;
export const Slider: ComponentMarker;
export const ProgressBar: ComponentMarker;
export const Toolbar: ComponentMarker;
export const Table: ComponentMarker;
export const TableSection: ComponentMarker;
export const TableRow: ComponentMarker;
export const TableCell: ComponentMarker;
export const TableColumn: ComponentMarker;
export const TableCaption: ComponentMarker;

export function jsx(
  type: typeof Fragment,
  props: WebCompatibleProps,
  key?: unknown,
): CompiledJsxNode[];
export function jsx(
  type: string | ComponentMarker,
  props: WebCompatibleProps,
  key?: unknown,
): CompiledJsxElement;
export const jsxs: typeof jsx;

export namespace JSX {
  type Element = CompiledJsxElement | CompiledJsxNode[];
  interface ElementChildrenAttribute {
    children: {};
  }
  interface IntrinsicElements {
    [elementName: string]: WebCompatibleProps;
  }
}
