import {
  TSX_PROTOCOL_V1_AUTOMATIC_ACTION_ID_PREFIX,
  TSX_PROTOCOL_V1_COMPONENT_IDENTITY_PREFIX,
  TSX_PROTOCOL_V1_GENERATED_ID_NAMESPACE,
  TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES,
} from "./generated/protocol.ts";

/** Namespace reserved for identities generated by the A3S runtime. */
export const A3S_GENERATED_ID_NAMESPACE_V1 = TSX_PROTOCOL_V1_GENERATED_ID_NAMESPACE;

/** Prefix for Node-local function-component instance identities. */
export const A3S_COMPONENT_IDENTITY_PREFIX_V1 = TSX_PROTOCOL_V1_COMPONENT_IDENTITY_PREFIX;

/** Prefix for action ids derived from native host paths and event props. */
export const A3S_AUTOMATIC_ACTION_ID_PREFIX_V1 = TSX_PROTOCOL_V1_AUTOMATIC_ACTION_ID_PREFIX;

/** Canonical version-1 identity for one Node-local function-component instance. */
export type A3sComponentIdentityV1 =
  `${typeof A3S_COMPONENT_IDENTITY_PREFIX_V1}${string}`;

/** Canonical version-1 action id generated from a native path and event prop. */
export type A3sAutomaticActionIdV1 =
  `${typeof A3S_AUTOMATIC_ACTION_ID_PREFIX_V1}${string}`;

const CONTROL_CHARACTER = /\p{Cc}/u;
const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder("utf-8", { fatal: true });

/** Returns whether a value is a canonical version-1 component identity. */
export function isA3sComponentIdentityV1(
  value: unknown,
): value is A3sComponentIdentityV1 {
  return isCanonicalSegmentIdentity(
    value,
    A3S_COMPONENT_IDENTITY_PREFIX_V1,
    2,
    Number.POSITIVE_INFINITY,
  );
}

/** Returns whether a value is a canonical, wire-safe automatic action id. */
export function isA3sAutomaticActionIdV1(
  value: unknown,
): value is A3sAutomaticActionIdV1 {
  return isCanonicalSegmentIdentity(
    value,
    A3S_AUTOMATIC_ACTION_ID_PREFIX_V1,
    2,
    TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES,
  );
}

export function createComponentIdentityV1(
  address: readonly string[],
): A3sComponentIdentityV1 {
  requireIdentitySegments(address, "component address", 2);
  return `${A3S_COMPONENT_IDENTITY_PREFIX_V1}${encodeIdentitySegmentsV1(address)}`;
}

export function createAutomaticActionIdV1(
  hostPath: readonly string[],
  eventName: string,
): A3sAutomaticActionIdV1 {
  requireIdentitySegments(hostPath, "automatic action host path", 1);
  requireIdentitySegment(eventName, "automatic action event name");
  const id = `${A3S_AUTOMATIC_ACTION_ID_PREFIX_V1}${encodeIdentitySegmentsV1([
    ...hostPath,
    eventName,
  ])}` as A3sAutomaticActionIdV1;
  if (textEncoder.encode(id).byteLength > TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES) {
    throw new RangeError(
      `automatic action id exceeds the ${TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES}-byte protocol limit; shorten its native key path`,
    );
  }
  return id;
}

export function encodeIdentitySegmentsV1(segments: readonly string[]): string {
  return segments
    .map((segment) => `${textEncoder.encode(segment).byteLength}:${segment}`)
    .join("");
}

export function assertExplicitActionIdV1(value: unknown): asserts value is string {
  if (typeof value !== "string" || value.length === 0) {
    throw new TypeError("A3S action ids must be non-empty strings");
  }
  if (value.trim().length === 0) {
    throw new TypeError("A3S action ids must contain non-whitespace text");
  }
  if (CONTROL_CHARACTER.test(value)) {
    throw new TypeError("A3S action ids cannot contain control characters");
  }
  if (textEncoder.encode(value).byteLength > TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES) {
    throw new TypeError(
      `A3S action id exceeds the ${TSX_PROTOCOL_V1_MAX_ACTION_ID_BYTES}-byte protocol limit`,
    );
  }
  if (isCanonicalArrayIndexName(value)) {
    throw new TypeError("A3S action ids cannot be canonical JavaScript array-index names");
  }
  if (value.startsWith(A3S_GENERATED_ID_NAMESPACE_V1)) {
    throw new TypeError(
      `${A3S_GENERATED_ID_NAMESPACE_V1} is reserved for framework-generated identities`,
    );
  }
}

export function isExplicitActionIdV1(value: unknown): value is string {
  try {
    assertExplicitActionIdV1(value);
    return true;
  } catch {
    return false;
  }
}

export function isAcceptedActionIdV1(value: unknown): value is string {
  return isExplicitActionIdV1(value) || isA3sAutomaticActionIdV1(value);
}

function isCanonicalSegmentIdentity(
  value: unknown,
  prefix: string,
  minimumSegments: number,
  maximumBytes: number,
): boolean {
  if (
    typeof value !== "string" ||
    !value.startsWith(prefix) ||
    CONTROL_CHARACTER.test(value) ||
    textEncoder.encode(value).byteLength > maximumBytes
  ) {
    return false;
  }

  const encoded = textEncoder.encode(value.slice(prefix.length));
  const segments: string[] = [];
  let cursor = 0;
  while (cursor < encoded.byteLength) {
    const lengthStart = cursor;
    while (cursor < encoded.byteLength && isAsciiDigit(encoded[cursor])) {
      cursor += 1;
    }
    if (cursor === lengthStart || cursor >= encoded.byteLength || encoded[cursor] !== 0x3a) {
      return false;
    }
    if (encoded[lengthStart] === 0x30 && cursor - lengthStart > 1) {
      return false;
    }
    let length = 0;
    for (let index = lengthStart; index < cursor; index += 1) {
      length = (length * 10) + encoded[index] - 0x30;
      if (!Number.isSafeInteger(length)) {
        return false;
      }
    }
    cursor += 1;
    if (
      !Number.isSafeInteger(length) ||
      length < 1 ||
      length > encoded.byteLength - cursor
    ) {
      return false;
    }
    let segment: string;
    try {
      segment = textDecoder.decode(encoded.subarray(cursor, cursor + length));
    } catch {
      return false;
    }
    segments.push(segment);
    cursor += length;
  }

  return segments.length >= minimumSegments &&
    `${prefix}${encodeIdentitySegmentsV1(segments)}` === value;
}

function requireIdentitySegments(
  segments: readonly string[],
  name: string,
  minimum: number,
): void {
  if (!Array.isArray(segments) || segments.length < minimum) {
    throw new TypeError(`${name} must contain at least ${minimum} segment(s)`);
  }
  for (let index = 0; index < segments.length; index += 1) {
    requireIdentitySegment(segments[index], `${name} segment ${index}`);
  }
}

function requireIdentitySegment(value: unknown, name: string): asserts value is string {
  if (typeof value !== "string" || value.length === 0) {
    throw new TypeError(`${name} must be a non-empty string`);
  }
  if (CONTROL_CHARACTER.test(value)) {
    throw new TypeError(`${name} cannot contain control characters`);
  }
}

function isAsciiDigit(value: number): boolean {
  return value >= 0x30 && value <= 0x39;
}

function isCanonicalArrayIndexName(value: string): boolean {
  if (!/^(?:0|[1-9][0-9]*)$/u.test(value)) {
    return false;
  }
  const index = Number(value);
  return Number.isInteger(index) && index >= 0 && index < 0xffff_ffff;
}
