use crate::native::{NativeElement, NativeRole};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum AccessibilityRole {
    Window,
    Group,
    Document,
    DocumentHead,
    DocumentBody,
    DocumentTitle,
    Metadata,
    ResourceLink,
    StyleSheet,
    Script,
    Template,
    Slot,
    StaticText,
    Abbreviation,
    Citation,
    Definition,
    DataValue,
    InsertedText,
    DeletedText,
    MarkedText,
    Time,
    Emphasis,
    StrongText,
    Code,
    KeyboardInput,
    SampleOutput,
    Variable,
    InlineQuote,
    Subscript,
    Superscript,
    SmallText,
    BoldText,
    ItalicText,
    StruckText,
    UnderlinedText,
    BidirectionalIsolate,
    BidirectionalOverride,
    Paragraph,
    PreformattedText,
    BlockQuote,
    ContactAddress,
    LineBreak,
    WordBreakOpportunity,
    NoBreakText,
    CenteredText,
    FontText,
    BigText,
    TeletypeText,
    Heading,
    HeadingGroup,
    Ruby,
    RubyBase,
    RubyText,
    RubyParenthesis,
    RubyTextContainer,
    Main,
    Navigation,
    Header,
    Footer,
    Article,
    Section,
    Aside,
    Search,
    Disclosure,
    DisclosureSummary,
    Figure,
    FigureCaption,
    DescriptionList,
    DescriptionTerm,
    DescriptionDetails,
    Image,
    Media,
    Canvas,
    EmbeddedContent,
    Button,
    Link,
    ImageMap,
    ImageMapArea,
    TextField,
    Checkbox,
    Switch,
    RadioGroup,
    RadioButton,
    Form,
    FieldSet,
    Legend,
    OptionGroup,
    Output,
    Meter,
    ComboBox,
    ListBox,
    ListBoxOption,
    Dialog,
    Popover,
    TabGroup,
    TabList,
    Tab,
    TabPanel,
    Menu,
    MenuItem,
    Separator,
    Slider,
    ProgressIndicator,
    Toolbar,
    Table,
    TableSection,
    TableRow,
    TableCell,
    TableColumn,
    TableCaption,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AccessibilityNode {
    pub role: AccessibilityRole,
    pub label: Option<String>,
    pub value: Option<String>,
    pub disabled: bool,
    pub required: bool,
    pub invalid: bool,
    pub selected: bool,
    pub checked: Option<bool>,
    pub expanded: Option<bool>,
    pub children: Vec<AccessibilityNode>,
}

impl AccessibilityNode {
    pub fn from_native(element: &NativeElement) -> Self {
        Self {
            role: accessibility_role(element.role),
            label: element.props.label.clone(),
            value: element.props.value.clone(),
            disabled: element.props.disabled,
            required: element.props.required,
            invalid: element.props.invalid,
            selected: element.props.selected,
            checked: element.props.checked,
            expanded: element.props.expanded,
            children: element
                .children
                .iter()
                .map(AccessibilityNode::from_native)
                .collect(),
        }
    }
}

pub fn accessibility_role(role: NativeRole) -> AccessibilityRole {
    match role {
        NativeRole::Window => AccessibilityRole::Window,
        NativeRole::View => AccessibilityRole::Group,
        NativeRole::Document => AccessibilityRole::Document,
        NativeRole::DocumentHead => AccessibilityRole::DocumentHead,
        NativeRole::DocumentBody => AccessibilityRole::DocumentBody,
        NativeRole::DocumentTitle => AccessibilityRole::DocumentTitle,
        NativeRole::Metadata => AccessibilityRole::Metadata,
        NativeRole::ResourceLink => AccessibilityRole::ResourceLink,
        NativeRole::StyleSheet => AccessibilityRole::StyleSheet,
        NativeRole::Script => AccessibilityRole::Script,
        NativeRole::Template => AccessibilityRole::Template,
        NativeRole::Slot => AccessibilityRole::Slot,
        NativeRole::Text => AccessibilityRole::StaticText,
        NativeRole::Abbreviation => AccessibilityRole::Abbreviation,
        NativeRole::Citation => AccessibilityRole::Citation,
        NativeRole::Definition => AccessibilityRole::Definition,
        NativeRole::DataValue => AccessibilityRole::DataValue,
        NativeRole::InsertedText => AccessibilityRole::InsertedText,
        NativeRole::DeletedText => AccessibilityRole::DeletedText,
        NativeRole::MarkedText => AccessibilityRole::MarkedText,
        NativeRole::Time => AccessibilityRole::Time,
        NativeRole::Emphasis => AccessibilityRole::Emphasis,
        NativeRole::StrongText => AccessibilityRole::StrongText,
        NativeRole::Code => AccessibilityRole::Code,
        NativeRole::KeyboardInput => AccessibilityRole::KeyboardInput,
        NativeRole::SampleOutput => AccessibilityRole::SampleOutput,
        NativeRole::Variable => AccessibilityRole::Variable,
        NativeRole::InlineQuote => AccessibilityRole::InlineQuote,
        NativeRole::Subscript => AccessibilityRole::Subscript,
        NativeRole::Superscript => AccessibilityRole::Superscript,
        NativeRole::SmallText => AccessibilityRole::SmallText,
        NativeRole::BoldText => AccessibilityRole::BoldText,
        NativeRole::ItalicText => AccessibilityRole::ItalicText,
        NativeRole::StruckText => AccessibilityRole::StruckText,
        NativeRole::UnderlinedText => AccessibilityRole::UnderlinedText,
        NativeRole::BidirectionalIsolate => AccessibilityRole::BidirectionalIsolate,
        NativeRole::BidirectionalOverride => AccessibilityRole::BidirectionalOverride,
        NativeRole::Paragraph => AccessibilityRole::Paragraph,
        NativeRole::PreformattedText => AccessibilityRole::PreformattedText,
        NativeRole::BlockQuote => AccessibilityRole::BlockQuote,
        NativeRole::ContactAddress => AccessibilityRole::ContactAddress,
        NativeRole::LineBreak => AccessibilityRole::LineBreak,
        NativeRole::WordBreakOpportunity => AccessibilityRole::WordBreakOpportunity,
        NativeRole::NoBreakText => AccessibilityRole::NoBreakText,
        NativeRole::CenteredText => AccessibilityRole::CenteredText,
        NativeRole::FontText => AccessibilityRole::FontText,
        NativeRole::BigText => AccessibilityRole::BigText,
        NativeRole::TeletypeText => AccessibilityRole::TeletypeText,
        NativeRole::Heading => AccessibilityRole::Heading,
        NativeRole::HeadingGroup => AccessibilityRole::HeadingGroup,
        NativeRole::Ruby => AccessibilityRole::Ruby,
        NativeRole::RubyBase => AccessibilityRole::RubyBase,
        NativeRole::RubyText => AccessibilityRole::RubyText,
        NativeRole::RubyParenthesis => AccessibilityRole::RubyParenthesis,
        NativeRole::RubyTextContainer => AccessibilityRole::RubyTextContainer,
        NativeRole::Main => AccessibilityRole::Main,
        NativeRole::Navigation => AccessibilityRole::Navigation,
        NativeRole::Header => AccessibilityRole::Header,
        NativeRole::Footer => AccessibilityRole::Footer,
        NativeRole::Article => AccessibilityRole::Article,
        NativeRole::Section => AccessibilityRole::Section,
        NativeRole::Aside => AccessibilityRole::Aside,
        NativeRole::Search => AccessibilityRole::Search,
        NativeRole::Disclosure => AccessibilityRole::Disclosure,
        NativeRole::DisclosureSummary => AccessibilityRole::DisclosureSummary,
        NativeRole::Figure => AccessibilityRole::Figure,
        NativeRole::FigureCaption => AccessibilityRole::FigureCaption,
        NativeRole::DescriptionList => AccessibilityRole::DescriptionList,
        NativeRole::DescriptionTerm => AccessibilityRole::DescriptionTerm,
        NativeRole::DescriptionDetails => AccessibilityRole::DescriptionDetails,
        NativeRole::Image => AccessibilityRole::Image,
        NativeRole::Media => AccessibilityRole::Media,
        NativeRole::Canvas => AccessibilityRole::Canvas,
        NativeRole::EmbeddedContent => AccessibilityRole::EmbeddedContent,
        NativeRole::Button => AccessibilityRole::Button,
        NativeRole::Link => AccessibilityRole::Link,
        NativeRole::ImageMap => AccessibilityRole::ImageMap,
        NativeRole::ImageMapArea => AccessibilityRole::ImageMapArea,
        NativeRole::TextField => AccessibilityRole::TextField,
        NativeRole::Checkbox => AccessibilityRole::Checkbox,
        NativeRole::Switch => AccessibilityRole::Switch,
        NativeRole::RadioGroup => AccessibilityRole::RadioGroup,
        NativeRole::Radio => AccessibilityRole::RadioButton,
        NativeRole::Form => AccessibilityRole::Form,
        NativeRole::FieldSet => AccessibilityRole::FieldSet,
        NativeRole::Legend => AccessibilityRole::Legend,
        NativeRole::OptionGroup => AccessibilityRole::OptionGroup,
        NativeRole::Output => AccessibilityRole::Output,
        NativeRole::Meter => AccessibilityRole::Meter,
        NativeRole::Select | NativeRole::ComboBox => AccessibilityRole::ComboBox,
        NativeRole::ListBox => AccessibilityRole::ListBox,
        NativeRole::ListBoxItem => AccessibilityRole::ListBoxOption,
        NativeRole::Dialog => AccessibilityRole::Dialog,
        NativeRole::Popover => AccessibilityRole::Popover,
        NativeRole::Tabs => AccessibilityRole::TabGroup,
        NativeRole::TabList => AccessibilityRole::TabList,
        NativeRole::Tab => AccessibilityRole::Tab,
        NativeRole::TabPanel => AccessibilityRole::TabPanel,
        NativeRole::Menu => AccessibilityRole::Menu,
        NativeRole::MenuItem => AccessibilityRole::MenuItem,
        NativeRole::Separator => AccessibilityRole::Separator,
        NativeRole::Slider => AccessibilityRole::Slider,
        NativeRole::ProgressBar => AccessibilityRole::ProgressIndicator,
        NativeRole::Toolbar => AccessibilityRole::Toolbar,
        NativeRole::Table => AccessibilityRole::Table,
        NativeRole::TableSection => AccessibilityRole::TableSection,
        NativeRole::TableRow => AccessibilityRole::TableRow,
        NativeRole::TableCell => AccessibilityRole::TableCell,
        NativeRole::TableColumn => AccessibilityRole::TableColumn,
        NativeRole::TableCaption => AccessibilityRole::TableCaption,
    }
}
