use crate::accessibility::accessibility_role;
use crate::html::HTML_TAG_METADATA_KEY;
use crate::native::{NativeElement, NativeRole};
use crate::style::PortableStyle;

use super::types::{NativeBackendKind, NativeControlState, NativeWidgetBlueprint};

pub fn native_widget_name(backend: NativeBackendKind, role: NativeRole) -> &'static str {
    match backend {
        NativeBackendKind::AppKit => appkit_widget_name(role),
        NativeBackendKind::WinUI => winui_widget_name(role),
        NativeBackendKind::Gtk4 => gtk4_widget_name(role),
        NativeBackendKind::Headless => "a3s_gui::HeadlessNode",
    }
}

pub fn widget_blueprint(
    backend: NativeBackendKind,
    element: &NativeElement,
) -> NativeWidgetBlueprint {
    NativeWidgetBlueprint {
        backend,
        widget_class: native_widget_name_for_element(backend, element).to_string(),
        role: element.role,
        accessibility_role: accessibility_role(element.role),
        label: element.props.label.clone(),
        value: element.props.value.clone(),
        action: element
            .props
            .action
            .clone()
            .or_else(|| element.props.web.primary_action().map(str::to_string)),
        class_name: element.props.web.class_name.clone(),
        control_state: NativeControlState::from_props(&element.props),
        style: element.props.web.style.clone(),
        portable_style: PortableStyle::from_web(&element.props.web),
        events: element.props.web.events.clone(),
        metadata: element.props.metadata.clone(),
    }
}

fn native_widget_name_for_element(
    backend: NativeBackendKind,
    element: &NativeElement,
) -> &'static str {
    if element.role == NativeRole::TextField
        && element
            .props
            .metadata
            .get(HTML_TAG_METADATA_KEY)
            .is_some_and(|tag| tag == "textarea")
    {
        return match backend {
            NativeBackendKind::AppKit => "NSTextField(textarea)",
            NativeBackendKind::WinUI => "Microsoft.UI.Xaml.Controls.TextBox(textarea)",
            NativeBackendKind::Gtk4 => "gtk::TextView",
            NativeBackendKind::Headless => "a3s_gui::HeadlessNode",
        };
    }

    if element.role == NativeRole::TextField
        && element
            .props
            .input_type
            .as_deref()
            .is_some_and(|input_type| input_type.trim().eq_ignore_ascii_case("search"))
    {
        return match backend {
            NativeBackendKind::AppKit => "NSSearchField",
            NativeBackendKind::WinUI => "Microsoft.UI.Xaml.Controls.TextBox(search)",
            NativeBackendKind::Gtk4 => "gtk::SearchEntry",
            NativeBackendKind::Headless => "a3s_gui::HeadlessNode",
        };
    }

    if element.role == NativeRole::TextField
        && element
            .props
            .input_type
            .as_deref()
            .is_some_and(|input_type| input_type.trim().eq_ignore_ascii_case("number"))
    {
        return match backend {
            NativeBackendKind::AppKit => "NSTextField(input)",
            NativeBackendKind::WinUI => "Microsoft.UI.Xaml.Controls.TextBox",
            NativeBackendKind::Gtk4 => "gtk::SpinButton",
            NativeBackendKind::Headless => "a3s_gui::HeadlessNode",
        };
    }

    if element.role == NativeRole::TextField
        && element
            .props
            .input_type
            .as_deref()
            .is_some_and(|input_type| input_type.trim().eq_ignore_ascii_case("password"))
    {
        return match backend {
            NativeBackendKind::AppKit => "NSSecureTextField",
            NativeBackendKind::WinUI => "Microsoft.UI.Xaml.Controls.PasswordBox",
            NativeBackendKind::Gtk4 => "gtk::PasswordEntry",
            NativeBackendKind::Headless => "a3s_gui::HeadlessNode",
        };
    }

    native_widget_name(backend, element.role)
}

fn appkit_widget_name(role: NativeRole) -> &'static str {
    match role {
        NativeRole::Window => "NSWindow",
        NativeRole::View => "NSView",
        NativeRole::Document => "NSView(document)",
        NativeRole::DocumentHead => "NSView(document-head)",
        NativeRole::DocumentBody => "NSView(document-body)",
        NativeRole::DocumentTitle => "NSTextField(document-title)",
        NativeRole::Metadata => "NSView(metadata)",
        NativeRole::ResourceLink => "NSView(resource-link)",
        NativeRole::StyleSheet => "NSView(style-sheet)",
        NativeRole::Script => "NSView(script)",
        NativeRole::Template => "NSView(template)",
        NativeRole::Slot => "NSView(slot)",
        NativeRole::Text => "NSTextField(label)",
        NativeRole::Abbreviation => "NSTextField(abbreviation)",
        NativeRole::Citation => "NSTextField(citation)",
        NativeRole::Definition => "NSTextField(definition)",
        NativeRole::DataValue => "NSTextField(data-value)",
        NativeRole::InsertedText => "NSTextField(inserted-text)",
        NativeRole::DeletedText => "NSTextField(deleted-text)",
        NativeRole::MarkedText => "NSTextField(marked-text)",
        NativeRole::Time => "NSTextField(time)",
        NativeRole::Emphasis => "NSTextField(emphasis)",
        NativeRole::StrongText => "NSTextField(strong-text)",
        NativeRole::Code => "NSTextField(code)",
        NativeRole::KeyboardInput => "NSTextField(keyboard-input)",
        NativeRole::SampleOutput => "NSTextField(sample-output)",
        NativeRole::Variable => "NSTextField(variable)",
        NativeRole::InlineQuote => "NSTextField(inline-quote)",
        NativeRole::Subscript => "NSTextField(subscript)",
        NativeRole::Superscript => "NSTextField(superscript)",
        NativeRole::SmallText => "NSTextField(small-text)",
        NativeRole::BoldText => "NSTextField(bold-text)",
        NativeRole::ItalicText => "NSTextField(italic-text)",
        NativeRole::StruckText => "NSTextField(struck-text)",
        NativeRole::UnderlinedText => "NSTextField(underlined-text)",
        NativeRole::BidirectionalIsolate => "NSTextField(bidi-isolate)",
        NativeRole::BidirectionalOverride => "NSTextField(bidi-override)",
        NativeRole::Paragraph => "NSView(paragraph)",
        NativeRole::PreformattedText => "NSView(preformatted-text)",
        NativeRole::BlockQuote => "NSView(block-quote)",
        NativeRole::ContactAddress => "NSView(contact-address)",
        NativeRole::LineBreak => "NSTextField(line-break)",
        NativeRole::WordBreakOpportunity => "NSTextField(word-break-opportunity)",
        NativeRole::NoBreakText => "NSView(no-break-text)",
        NativeRole::CenteredText => "NSView(centered-text)",
        NativeRole::FontText => "NSView(font-text)",
        NativeRole::BigText => "NSView(big-text)",
        NativeRole::TeletypeText => "NSView(teletype-text)",
        NativeRole::Applet => "NSView(applet)",
        NativeRole::BackgroundSound => "NSView(background-sound)",
        NativeRole::Frame => "NSView(frame)",
        NativeRole::FrameSet => "NSView(frameset)",
        NativeRole::NoEmbedFallback => "NSView(noembed-fallback)",
        NativeRole::NoFramesFallback => "NSView(noframes-fallback)",
        NativeRole::Marquee => "NSView(marquee)",
        NativeRole::Math => "NSView(math)",
        NativeRole::NextId => "NSView(nextid)",
        NativeRole::SelectedContent => "NSView(selected-content)",
        NativeRole::Heading => "NSTextField(heading)",
        NativeRole::HeadingGroup => "NSView(heading-group)",
        NativeRole::Ruby => "NSView(ruby)",
        NativeRole::RubyBase => "NSTextField(ruby-base)",
        NativeRole::RubyText => "NSTextField(ruby-text)",
        NativeRole::RubyParenthesis => "NSTextField(ruby-parenthesis)",
        NativeRole::RubyTextContainer => "NSView(ruby-text-container)",
        NativeRole::Main => "NSView(main)",
        NativeRole::Navigation => "NSView(navigation)",
        NativeRole::Header => "NSView(header)",
        NativeRole::Footer => "NSView(footer)",
        NativeRole::Article => "NSView(article)",
        NativeRole::Section => "NSView(section)",
        NativeRole::Aside => "NSView(aside)",
        NativeRole::Search => "NSView(search)",
        NativeRole::Disclosure => "NSView(disclosure)",
        NativeRole::DisclosureSummary => "NSButton(disclosure-summary)",
        NativeRole::Figure => "NSView(figure)",
        NativeRole::FigureCaption => "NSTextField(figure-caption)",
        NativeRole::DescriptionList => "NSView(description-list)",
        NativeRole::DescriptionTerm => "NSTextField(description-term)",
        NativeRole::DescriptionDetails => "NSView(description-details)",
        NativeRole::Image => "NSImageView",
        NativeRole::Media => "AVPlayerView",
        NativeRole::Canvas => "NSView(canvas)",
        NativeRole::EmbeddedContent => "NSView(embedded-content)",
        NativeRole::Button => "NSButton",
        NativeRole::Link => "NSButton(link)",
        NativeRole::ImageMap => "NSView(image-map)",
        NativeRole::ImageMapArea => "NSButton(image-map-area)",
        NativeRole::TextField => "NSTextField(input)",
        NativeRole::Checkbox => "NSButton(checkbox)",
        NativeRole::Switch => "NSSwitch",
        NativeRole::RadioGroup => "NSStackView(radio-group)",
        NativeRole::Radio => "NSButton(radio)",
        NativeRole::Form => "NSView(form)",
        NativeRole::FieldSet => "NSView(fieldset)",
        NativeRole::Legend => "NSTextField(legend)",
        NativeRole::OptionGroup => "NSView(option-group)",
        NativeRole::Output => "NSTextField(output)",
        NativeRole::Meter => "NSProgressIndicator(meter)",
        NativeRole::Select | NativeRole::ComboBox => "NSComboBox",
        NativeRole::ListBox => "NSScrollView+NSStackView",
        NativeRole::ListBoxItem => "NSButton(list-row)",
        NativeRole::Dialog => "NSPanel",
        NativeRole::Popover => "NSPopover",
        NativeRole::Tabs => "NSTabView",
        NativeRole::TabList => "NSTabView",
        NativeRole::Tab => "NSTabViewItem",
        NativeRole::TabPanel => "NSView",
        NativeRole::Menu => "NSMenu",
        NativeRole::MenuItem => "NSMenuItem",
        NativeRole::Separator => "NSBox(separator)",
        NativeRole::Slider => "NSSlider",
        NativeRole::ProgressBar => "NSProgressIndicator",
        NativeRole::Toolbar => "NSStackView(toolbar)",
        NativeRole::Table => "NSTableView",
        NativeRole::TableSection => "NSView(table-section)",
        NativeRole::TableRow => "NSTableRowView",
        NativeRole::TableCell => "NSTableCellView",
        NativeRole::TableColumn => "NSTableColumn",
        NativeRole::TableCaption => "NSTextField(table-caption)",
    }
}
fn winui_widget_name(role: NativeRole) -> &'static str {
    match role {
        NativeRole::Window => "Microsoft.UI.Xaml.Window",
        NativeRole::View => "Microsoft.UI.Xaml.Controls.StackPanel",
        NativeRole::Document => "Microsoft.UI.Xaml.Controls.StackPanel(document)",
        NativeRole::DocumentHead => "Microsoft.UI.Xaml.Controls.StackPanel(document-head)",
        NativeRole::DocumentBody => "Microsoft.UI.Xaml.Controls.StackPanel(document-body)",
        NativeRole::DocumentTitle => "Microsoft.UI.Xaml.Controls.TextBlock(document-title)",
        NativeRole::Metadata => "Microsoft.UI.Xaml.Controls.StackPanel(metadata)",
        NativeRole::ResourceLink => "Microsoft.UI.Xaml.Controls.StackPanel(resource-link)",
        NativeRole::StyleSheet => "Microsoft.UI.Xaml.Controls.StackPanel(style-sheet)",
        NativeRole::Script => "Microsoft.UI.Xaml.Controls.StackPanel(script)",
        NativeRole::Template => "Microsoft.UI.Xaml.Controls.StackPanel(template)",
        NativeRole::Slot => "Microsoft.UI.Xaml.Controls.StackPanel(slot)",
        NativeRole::Text => "Microsoft.UI.Xaml.Controls.TextBlock",
        NativeRole::Abbreviation => "Microsoft.UI.Xaml.Controls.TextBlock(abbreviation)",
        NativeRole::Citation => "Microsoft.UI.Xaml.Controls.TextBlock(citation)",
        NativeRole::Definition => "Microsoft.UI.Xaml.Controls.TextBlock(definition)",
        NativeRole::DataValue => "Microsoft.UI.Xaml.Controls.TextBlock(data-value)",
        NativeRole::InsertedText => "Microsoft.UI.Xaml.Controls.TextBlock(inserted-text)",
        NativeRole::DeletedText => "Microsoft.UI.Xaml.Controls.TextBlock(deleted-text)",
        NativeRole::MarkedText => "Microsoft.UI.Xaml.Controls.TextBlock(marked-text)",
        NativeRole::Time => "Microsoft.UI.Xaml.Controls.TextBlock(time)",
        NativeRole::Emphasis => "Microsoft.UI.Xaml.Controls.TextBlock(emphasis)",
        NativeRole::StrongText => "Microsoft.UI.Xaml.Controls.TextBlock(strong-text)",
        NativeRole::Code => "Microsoft.UI.Xaml.Controls.TextBlock(code)",
        NativeRole::KeyboardInput => "Microsoft.UI.Xaml.Controls.TextBlock(keyboard-input)",
        NativeRole::SampleOutput => "Microsoft.UI.Xaml.Controls.TextBlock(sample-output)",
        NativeRole::Variable => "Microsoft.UI.Xaml.Controls.TextBlock(variable)",
        NativeRole::InlineQuote => "Microsoft.UI.Xaml.Controls.TextBlock(inline-quote)",
        NativeRole::Subscript => "Microsoft.UI.Xaml.Controls.TextBlock(subscript)",
        NativeRole::Superscript => "Microsoft.UI.Xaml.Controls.TextBlock(superscript)",
        NativeRole::SmallText => "Microsoft.UI.Xaml.Controls.TextBlock(small-text)",
        NativeRole::BoldText => "Microsoft.UI.Xaml.Controls.TextBlock(bold-text)",
        NativeRole::ItalicText => "Microsoft.UI.Xaml.Controls.TextBlock(italic-text)",
        NativeRole::StruckText => "Microsoft.UI.Xaml.Controls.TextBlock(struck-text)",
        NativeRole::UnderlinedText => "Microsoft.UI.Xaml.Controls.TextBlock(underlined-text)",
        NativeRole::BidirectionalIsolate => "Microsoft.UI.Xaml.Controls.TextBlock(bidi-isolate)",
        NativeRole::BidirectionalOverride => "Microsoft.UI.Xaml.Controls.TextBlock(bidi-override)",
        NativeRole::Paragraph => "Microsoft.UI.Xaml.Controls.StackPanel(paragraph)",
        NativeRole::PreformattedText => "Microsoft.UI.Xaml.Controls.StackPanel(preformatted-text)",
        NativeRole::BlockQuote => "Microsoft.UI.Xaml.Controls.StackPanel(block-quote)",
        NativeRole::ContactAddress => "Microsoft.UI.Xaml.Controls.StackPanel(contact-address)",
        NativeRole::LineBreak => "Microsoft.UI.Xaml.Controls.TextBlock(line-break)",
        NativeRole::WordBreakOpportunity => {
            "Microsoft.UI.Xaml.Controls.TextBlock(word-break-opportunity)"
        }
        NativeRole::NoBreakText => "Microsoft.UI.Xaml.Controls.StackPanel(no-break-text)",
        NativeRole::CenteredText => "Microsoft.UI.Xaml.Controls.StackPanel(centered-text)",
        NativeRole::FontText => "Microsoft.UI.Xaml.Controls.StackPanel(font-text)",
        NativeRole::BigText => "Microsoft.UI.Xaml.Controls.StackPanel(big-text)",
        NativeRole::TeletypeText => "Microsoft.UI.Xaml.Controls.StackPanel(teletype-text)",
        NativeRole::Applet => "Microsoft.UI.Xaml.Controls.StackPanel(applet)",
        NativeRole::BackgroundSound => "Microsoft.UI.Xaml.Controls.StackPanel(background-sound)",
        NativeRole::Frame => "Microsoft.UI.Xaml.Controls.StackPanel(frame)",
        NativeRole::FrameSet => "Microsoft.UI.Xaml.Controls.StackPanel(frameset)",
        NativeRole::NoEmbedFallback => "Microsoft.UI.Xaml.Controls.StackPanel(noembed-fallback)",
        NativeRole::NoFramesFallback => "Microsoft.UI.Xaml.Controls.StackPanel(noframes-fallback)",
        NativeRole::Marquee => "Microsoft.UI.Xaml.Controls.StackPanel(marquee)",
        NativeRole::Math => "Microsoft.UI.Xaml.Controls.StackPanel(math)",
        NativeRole::NextId => "Microsoft.UI.Xaml.Controls.StackPanel(nextid)",
        NativeRole::SelectedContent => "Microsoft.UI.Xaml.Controls.StackPanel(selected-content)",
        NativeRole::Heading => "Microsoft.UI.Xaml.Controls.TextBlock(heading)",
        NativeRole::HeadingGroup => "Microsoft.UI.Xaml.Controls.StackPanel(heading-group)",
        NativeRole::Ruby => "Microsoft.UI.Xaml.Controls.StackPanel(ruby)",
        NativeRole::RubyBase => "Microsoft.UI.Xaml.Controls.TextBlock(ruby-base)",
        NativeRole::RubyText => "Microsoft.UI.Xaml.Controls.TextBlock(ruby-text)",
        NativeRole::RubyParenthesis => "Microsoft.UI.Xaml.Controls.TextBlock(ruby-parenthesis)",
        NativeRole::RubyTextContainer => {
            "Microsoft.UI.Xaml.Controls.StackPanel(ruby-text-container)"
        }
        NativeRole::Main => "Microsoft.UI.Xaml.Controls.StackPanel(main)",
        NativeRole::Navigation => "Microsoft.UI.Xaml.Controls.StackPanel(navigation)",
        NativeRole::Header => "Microsoft.UI.Xaml.Controls.StackPanel(header)",
        NativeRole::Footer => "Microsoft.UI.Xaml.Controls.StackPanel(footer)",
        NativeRole::Article => "Microsoft.UI.Xaml.Controls.StackPanel(article)",
        NativeRole::Section => "Microsoft.UI.Xaml.Controls.StackPanel(section)",
        NativeRole::Aside => "Microsoft.UI.Xaml.Controls.StackPanel(aside)",
        NativeRole::Search => "Microsoft.UI.Xaml.Controls.StackPanel(search)",
        NativeRole::Disclosure => "Microsoft.UI.Xaml.Controls.StackPanel(disclosure)",
        NativeRole::DisclosureSummary => "Microsoft.UI.Xaml.Controls.Button(disclosure-summary)",
        NativeRole::Figure => "Microsoft.UI.Xaml.Controls.StackPanel(figure)",
        NativeRole::FigureCaption => "Microsoft.UI.Xaml.Controls.TextBlock(figure-caption)",
        NativeRole::DescriptionList => "Microsoft.UI.Xaml.Controls.StackPanel(description-list)",
        NativeRole::DescriptionTerm => "Microsoft.UI.Xaml.Controls.TextBlock(description-term)",
        NativeRole::DescriptionDetails => {
            "Microsoft.UI.Xaml.Controls.StackPanel(description-details)"
        }
        NativeRole::Image => "Microsoft.UI.Xaml.Controls.Image",
        NativeRole::Media => "Microsoft.UI.Xaml.Controls.MediaPlayerElement",
        NativeRole::Canvas => "Microsoft.UI.Xaml.Controls.Canvas",
        NativeRole::EmbeddedContent => {
            "Microsoft.UI.Xaml.Controls.ContentControl(embedded-content)"
        }
        NativeRole::Button => "Microsoft.UI.Xaml.Controls.Button",
        NativeRole::Link => "Microsoft.UI.Xaml.Controls.HyperlinkButton",
        NativeRole::ImageMap => "Microsoft.UI.Xaml.Controls.Canvas(image-map)",
        NativeRole::ImageMapArea => "Microsoft.UI.Xaml.Controls.HyperlinkButton(image-map-area)",
        NativeRole::TextField => "Microsoft.UI.Xaml.Controls.TextBox",
        NativeRole::Checkbox => "Microsoft.UI.Xaml.Controls.CheckBox",
        NativeRole::Switch => "Microsoft.UI.Xaml.Controls.ToggleSwitch",
        NativeRole::RadioGroup => "Microsoft.UI.Xaml.Controls.RadioButtons",
        NativeRole::Radio => "Microsoft.UI.Xaml.Controls.RadioButton",
        NativeRole::Form => "Microsoft.UI.Xaml.Controls.StackPanel(form)",
        NativeRole::FieldSet => "Microsoft.UI.Xaml.Controls.StackPanel(fieldset)",
        NativeRole::Legend => "Microsoft.UI.Xaml.Controls.TextBlock(legend)",
        NativeRole::OptionGroup => "Microsoft.UI.Xaml.Controls.StackPanel(option-group)",
        NativeRole::Output => "Microsoft.UI.Xaml.Controls.TextBlock(output)",
        NativeRole::Meter => "Microsoft.UI.Xaml.Controls.ProgressBar(meter)",
        NativeRole::Select | NativeRole::ComboBox => "Microsoft.UI.Xaml.Controls.ComboBox",
        NativeRole::ListBox => "Microsoft.UI.Xaml.Controls.ListView",
        NativeRole::ListBoxItem => "Microsoft.UI.Xaml.Controls.ListViewItem",
        NativeRole::Dialog => "Microsoft.UI.Xaml.Controls.ContentDialog",
        NativeRole::Popover => "Microsoft.UI.Xaml.Controls.ToolTip",
        NativeRole::Tabs => "Microsoft.UI.Xaml.Controls.TabView",
        NativeRole::TabList => "Microsoft.UI.Xaml.Controls.TabView",
        NativeRole::Tab => "Microsoft.UI.Xaml.Controls.TabViewItem",
        NativeRole::TabPanel => "Microsoft.UI.Xaml.Controls.Grid",
        NativeRole::Menu => "Microsoft.UI.Xaml.Controls.StackPanel(menu)",
        NativeRole::MenuItem => "Microsoft.UI.Xaml.Controls.Button(menu-item)",
        NativeRole::Separator => "Microsoft.UI.Xaml.Controls.Border(separator)",
        NativeRole::Slider => "Microsoft.UI.Xaml.Controls.Slider",
        NativeRole::ProgressBar => "Microsoft.UI.Xaml.Controls.ProgressBar",
        NativeRole::Toolbar => "Microsoft.UI.Xaml.Controls.StackPanel(toolbar)",
        NativeRole::Table => "Microsoft.UI.Xaml.Controls.Grid(table)",
        NativeRole::TableSection => "Microsoft.UI.Xaml.Controls.StackPanel(table-section)",
        NativeRole::TableRow => "Microsoft.UI.Xaml.Controls.Grid(row)",
        NativeRole::TableCell => "Microsoft.UI.Xaml.Controls.Grid(cell)",
        NativeRole::TableColumn => "Microsoft.UI.Xaml.Controls.Grid(column)",
        NativeRole::TableCaption => "Microsoft.UI.Xaml.Controls.TextBlock(table-caption)",
    }
}

fn gtk4_widget_name(role: NativeRole) -> &'static str {
    match role {
        NativeRole::Window => "gtk::ApplicationWindow",
        NativeRole::View => "gtk::Box",
        NativeRole::Document => "gtk::Box(document)",
        NativeRole::DocumentHead => "gtk::Box(document-head)",
        NativeRole::DocumentBody => "gtk::Box(document-body)",
        NativeRole::DocumentTitle => "gtk::Label(document-title)",
        NativeRole::Metadata => "gtk::Box(metadata)",
        NativeRole::ResourceLink => "gtk::Box(resource-link)",
        NativeRole::StyleSheet => "gtk::Box(style-sheet)",
        NativeRole::Script => "gtk::Box(script)",
        NativeRole::Template => "gtk::Box(template)",
        NativeRole::Slot => "gtk::Box(slot)",
        NativeRole::Text => "gtk::Label",
        NativeRole::Abbreviation => "gtk::Label(abbreviation)",
        NativeRole::Citation => "gtk::Label(citation)",
        NativeRole::Definition => "gtk::Label(definition)",
        NativeRole::DataValue => "gtk::Label(data-value)",
        NativeRole::InsertedText => "gtk::Label(inserted-text)",
        NativeRole::DeletedText => "gtk::Label(deleted-text)",
        NativeRole::MarkedText => "gtk::Label(marked-text)",
        NativeRole::Time => "gtk::Label(time)",
        NativeRole::Emphasis => "gtk::Label(emphasis)",
        NativeRole::StrongText => "gtk::Label(strong-text)",
        NativeRole::Code => "gtk::Label(code)",
        NativeRole::KeyboardInput => "gtk::Label(keyboard-input)",
        NativeRole::SampleOutput => "gtk::Label(sample-output)",
        NativeRole::Variable => "gtk::Label(variable)",
        NativeRole::InlineQuote => "gtk::Label(inline-quote)",
        NativeRole::Subscript => "gtk::Label(subscript)",
        NativeRole::Superscript => "gtk::Label(superscript)",
        NativeRole::SmallText => "gtk::Label(small-text)",
        NativeRole::BoldText => "gtk::Label(bold-text)",
        NativeRole::ItalicText => "gtk::Label(italic-text)",
        NativeRole::StruckText => "gtk::Label(struck-text)",
        NativeRole::UnderlinedText => "gtk::Label(underlined-text)",
        NativeRole::BidirectionalIsolate => "gtk::Label(bidi-isolate)",
        NativeRole::BidirectionalOverride => "gtk::Label(bidi-override)",
        NativeRole::Paragraph => "gtk::Box(paragraph)",
        NativeRole::PreformattedText => "gtk::Box(preformatted-text)",
        NativeRole::BlockQuote => "gtk::Box(block-quote)",
        NativeRole::ContactAddress => "gtk::Box(contact-address)",
        NativeRole::LineBreak => "gtk::Label(line-break)",
        NativeRole::WordBreakOpportunity => "gtk::Label(word-break-opportunity)",
        NativeRole::NoBreakText => "gtk::Box(no-break-text)",
        NativeRole::CenteredText => "gtk::Box(centered-text)",
        NativeRole::FontText => "gtk::Box(font-text)",
        NativeRole::BigText => "gtk::Box(big-text)",
        NativeRole::TeletypeText => "gtk::Box(teletype-text)",
        NativeRole::Applet => "gtk::Box(applet)",
        NativeRole::BackgroundSound => "gtk::Box(background-sound)",
        NativeRole::Frame => "gtk::Box(frame)",
        NativeRole::FrameSet => "gtk::Box(frameset)",
        NativeRole::NoEmbedFallback => "gtk::Box(noembed-fallback)",
        NativeRole::NoFramesFallback => "gtk::Box(noframes-fallback)",
        NativeRole::Marquee => "gtk::Box(marquee)",
        NativeRole::Math => "gtk::Box(math)",
        NativeRole::NextId => "gtk::Box(nextid)",
        NativeRole::SelectedContent => "gtk::Box(selected-content)",
        NativeRole::Heading => "gtk::Label(heading)",
        NativeRole::HeadingGroup => "gtk::Box(heading-group)",
        NativeRole::Ruby => "gtk::Box(ruby)",
        NativeRole::RubyBase => "gtk::Label(ruby-base)",
        NativeRole::RubyText => "gtk::Label(ruby-text)",
        NativeRole::RubyParenthesis => "gtk::Label(ruby-parenthesis)",
        NativeRole::RubyTextContainer => "gtk::Box(ruby-text-container)",
        NativeRole::Main => "gtk::Box(main)",
        NativeRole::Navigation => "gtk::Box(navigation)",
        NativeRole::Header => "gtk::Box(header)",
        NativeRole::Footer => "gtk::Box(footer)",
        NativeRole::Article => "gtk::Box(article)",
        NativeRole::Section => "gtk::Box(section)",
        NativeRole::Aside => "gtk::Box(aside)",
        NativeRole::Search => "gtk::Box(search)",
        NativeRole::Disclosure => "gtk::Box(disclosure)",
        NativeRole::DisclosureSummary => "gtk::Button(disclosure-summary)",
        NativeRole::Figure => "gtk::Box(figure)",
        NativeRole::FigureCaption => "gtk::Label(figure-caption)",
        NativeRole::DescriptionList => "gtk::Box(description-list)",
        NativeRole::DescriptionTerm => "gtk::Label(description-term)",
        NativeRole::DescriptionDetails => "gtk::Box(description-details)",
        NativeRole::Image => "gtk::Picture",
        NativeRole::Media => "gtk::Video",
        NativeRole::Canvas => "gtk::DrawingArea",
        NativeRole::EmbeddedContent => "gtk::Box(embedded-content)",
        NativeRole::Button => "gtk::Button",
        NativeRole::Link => "gtk::LinkButton",
        NativeRole::ImageMap => "gtk::DrawingArea(image-map)",
        NativeRole::ImageMapArea => "gtk::LinkButton(image-map-area)",
        NativeRole::TextField => "gtk::Entry",
        NativeRole::Checkbox => "gtk::CheckButton",
        NativeRole::Switch => "gtk::Switch",
        NativeRole::RadioGroup => "gtk::Box(radio-group)",
        NativeRole::Radio => "gtk::CheckButton(radio)",
        NativeRole::Form => "gtk::Box(form)",
        NativeRole::FieldSet => "gtk::Box(fieldset)",
        NativeRole::Legend => "gtk::Label(legend)",
        NativeRole::OptionGroup => "gtk::Box(option-group)",
        NativeRole::Output => "gtk::Label(output)",
        NativeRole::Meter => "gtk::ProgressBar(meter)",
        NativeRole::Select | NativeRole::ComboBox => "gtk::DropDown",
        NativeRole::ListBox => "gtk::ListBox",
        NativeRole::ListBoxItem => "gtk::ListBoxRow",
        NativeRole::Dialog => "gtk::Dialog",
        NativeRole::Popover => "gtk::Popover",
        NativeRole::Tabs => "gtk::Notebook",
        NativeRole::TabList => "gtk::Notebook",
        NativeRole::Tab => "gtk::Label(tab)",
        NativeRole::TabPanel => "gtk::Box",
        NativeRole::Menu => "gio::Menu",
        NativeRole::MenuItem => "gio::MenuItem",
        NativeRole::Separator => "gtk::Separator",
        NativeRole::Slider => "gtk::Scale",
        NativeRole::ProgressBar => "gtk::ProgressBar",
        NativeRole::Toolbar => "gtk::Box(toolbar)",
        NativeRole::Table => "gtk::Grid(table)",
        NativeRole::TableSection => "gtk::Box(table-section)",
        NativeRole::TableRow => "gtk::Grid(row)",
        NativeRole::TableCell => "gtk::Grid(cell)",
        NativeRole::TableColumn => "gtk::ColumnViewColumn",
        NativeRole::TableCaption => "gtk::Label(table-caption)",
    }
}
